user_name: "{{ ansible_env.USER }}"
home: "{{ ansible_env.HOME }}"
ansible_python_interpreter: /usr/bin/python3
stow_dir: "{{ home }}/.local/stow"
files: "{{ role_path }}/files"

# dotfiles_user_home: "{{ '~' | expanduser }}"
# dotfiles_home: "{{ dotfiles_user_home }}/.dotfiles"
