# ansible_python_interpreter: /usr/bin/python3

user_name: "{{ ansible_env.USER }}"
home: "{{ ansible_env.HOME }}"

xdg_config_home: "{{ ansible_env.XDG_CONFIG_HOME | default(ansible_env.HOME + '/.config') }}"
xdg_data_home: "{{ ansible_env.XDG_DATA_HOME | default(ansible_env.HOME + '/.local/share') }}"

role_files: "{{ role_path }}/files"
stow_dir: "{{ home }}/.local/stow"

software: "{{ playbook_dir }}/software"

nproc: 7  # The number of processing units to use in parallel tasks.

# "{{ '~' | expanduser }}"
