#!/usr/bin/env zsh
#                                       ███ ██ ███
#                                      ██░ ░░ ░░██
#      ██████ ██████  ██████  █████   ░██   ██ ░██   █████
#     ░░░░██ ░██░░░██░░██░░█ ██░░░██ ██████░██ ░██  ██░░░██
#        ██  ░██  ░██ ░██ ░ ░██  ░██░░░██░ ░██ ░██ ░███████
#       ██   ░██████  ░██   ░██  ░██  ░██  ░██ ░██ ░██░░░░
#  ██  ██████░██░░░   ███   ░░█████   ░██  ░██ ░██ ░░█████
# ░░  ░░░░░░ ░██     ░░░     ░░░░░    ░░   ░░  ░░   ░░░░░
#            ░░

# Executes commands at login pre-zshrc.


# WORDCHARS (non-alphanumeric chars treated as part of a word)
# You can also tweak this if you'd prefer ^w to break on dot, underscore, etc.
export WORDCHARS='*?[]~=&;!#$%^(){}<>'


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  WSL
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# $IS_WSL environment variable existed in the WSL 1 version.
# $WSL_DISTRO_NAME variable exists in the current WSL 2 version.
# -n : true if length of string is non-zero.
if [[ -n "$IS_WSL" || -n "$WSL_DISTRO_NAME" ]]
then  # We are in wsl.
  export WINDOWS_HOST_IP=$(awk '/nameserver/ {print $2}' /etc/resolv.conf)
  export WINDOWS_USER="$(cmd.exe /C "echo %USERNAME%" 2>/dev/null | tr -d '\r')"
fi


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  Paths
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
path+=(
  /usr/local/{bin,sbin}
  /opt/visit/bin
  /opt/ParaView-5.8.1/bin
)

# # Set the list of directories that cd searches.
# cdpath=(
#   $HOME/.config
#   $cdpath
# )

# Homebrew {{{
if whence /home/linuxbrew/.linuxbrew/bin/brew > /dev/null 2>&1
then
  local BREWCACHE="$HOME/.cache/Homebrew/brewenv.zsh"

  if [[ ! -s $BREWCACHE(#q.md-7N) ]]
  then
      /home/linuxbrew/.linuxbrew/bin/brew shellenv > $BREWCACHE 2> /dev/null
  fi
  source $BREWCACHE

  # Enable completion for brew and programs installes with brew.
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi
# }}}


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  Editors
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

# export EDITOR VISUAL
if (( $+commands[nvim] ))
then
  export EDITOR='nvim'
  export VISUAL="$EDITOR"
  export DIFFPROG='nvim -d'
else
  export EDITOR='vim'
fi

export PAGER='less -R'


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  Browser
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
if [[ -f /opt/vivaldi/vivaldi ]]
then
  export BROWSER='/opt/vivaldi/vivaldi'
fi


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  Language
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

# if [[ -z "$LANG" ]]
# then
#     export LANG='en_US.UTF-8'
#     export LANGUAGE=en_US.UTF-8
# fi


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  Man
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
export MANWIDTH=80  # The width of the text column in the man.

# Tie together the scalar $MANPATH and the array $manpath
# in the same way that $PATH and $path ties.
typeset -T MANPATH manpath

# Ensure array do not contain duplicates.
typeset -gU manpath

# # Use `bat` as a colorizing pager for `man`
# export MANPAGER="sh -c 'col -bx | bat -l man -p'"


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  Less
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

# Set the default Less options.
# Mouse-wheel scrolling has been disabled  -X and -F (exit if the content
# fits on one screen) to enable it.

#  -F    Exit if the content fits on one screen
#  -g    Highlights just the current match of any searched string.
#  -i    Case-insensitive searches.
#  -M    Shows more detailed prompt, including file position.
#  -N    Shows line numbers (useful for source code viewing).
#  -R / --RAW-CONTROL-CHARS
#  -S    Disables line wrap ("chop long lines"). Long
#        lines can be seen by side scrolling.
#  -X    Leave file contents on screen when less exits.
#  -?    Shows help.
#  +F    Follow mode for log.
#  -w / --hilite-unread
#        Temporarily highlights the first "new" line
#        after a forward movement of a full page.
#  -z-4  Move page not on the full high of the screen
#        but on high minus 4 lines

# export LESS='-F -i -M -R -S -w -z-3'
# export LESS='-F -i -M -R -S -z-3'
export LESS='-i -M -R -S -z-3'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] ))
then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

export LESSHISTFILE="$HOME/.cache/lesshst"


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  Colored man pages
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

# export LESS_TERMCAP_mb=$'\e[01;31m'     # Begins blinking.
export LESS_TERMCAP_md=$'\e[01;97m'     # Begins bold.
export LESS_TERMCAP_so=$'\e[00;47;30m'  # Begins standout-mode.
export LESS_TERMCAP_us=$'\e[04;97m'     # Begins underline.
export LESS_TERMCAP_me=$'\e[0m'         # Ends mode.
export LESS_TERMCAP_se=$'\e[0m'         # Ends standout-mode.
export LESS_TERMCAP_ue=$'\e[0m'         # Ends underline.


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  LS_COLORS
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# Specification:
#
#   LS_COLORS='di=1:fi=0:...:or=31:*.deb=90'
#
# The '*.deb=90' parameter above tells 'ls' to display any files
# ending with a '.deb' extension using the color specified, 90 or dark grey
# in this case. This can be applied to any types of files (eg. you could
# use '*.jpg=33' to make JPEG files appear orange).
#
# The $LS_COLORS variable aldo used to color the zsh comletions.

# Tie together the scalar $LS_COLORS and the array $ls_colors in the same way
# that $PATH and $path ties.
typeset -T LS_COLORS ls_colors

# Here the ';' chars need to be escaped by '\' (for example: di=1\;36), other
# way they somewhy will be converted to ':' chars. Or it is also work to
# enclose them in quotes.
export ls_colors=(
  'di=1;36'   # Directory : bold; cyan
  'fi=0'      # File : default
  'ln=35'     # Symbolic Link : purple
  'pi=33'     # Fifo file
  'so=32'     # Socket file
  'bd=30;46'  # Block (buffered) special file : black; cyan background
  'cd=34;43'  # Character (unbuffered) special file
  # 'or'        # (ORPHAN) Symbolic link pointing to an orphaned non-existent file
  # 'mi'        # Non-existent file pointed to by a symbolic link (visible when you type ls -l)
  'su=30;41'  # File that is setuid (u+s)
  'sg=30;46'  # File that is setgid (g+s)
  'tw=30;42'  # Directory that is sticky and other-writable (+t,o+w)
  'ow=30;43'  # Directory that is other-writable (o+w) and not sticky
  'ex=31'     # File which is executable (ie. has ‘x’ set in permissions).
)


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  Bat
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
if (( $+commands[bat] ))
then
  export BAT_PAGER="less ${LESS}"
  # export BAT_PAGER="less -RF"
fi


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  Ripgrep
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
if (( $+commands[rg] ))
then
  export RIPGREP_CONFIG_PATH=$HOME/.config/rg/config
fi

#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  Par (paragraph formating)
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# The following string is recommended in par man.
export PARINIT='rTbgqR B=.,?_A_a Q=_s>|'


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  XDG
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# export XDG_RUNTIME_DIR="/tmp/runtime-$USER"

#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  pkg-config
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

# # Create parameter and array and tie them together in the manner of $PATH
# # and $path.
# typeset -T -gU PKG_CONFIG_PATH pkg_config_path
# export PKG_CONFIG_PATH
#
# pkg_config_path=(
#     /usr/lib/pkgconfig
#     /usr/lib/x86_64-linux-gnu/pkgconfig
#     /usr/share/pkgconfig
#     /opt/petsc-real/lib/pkgconfig
#     /opt/slepc-real/lib/pkgconfig
# )
#

#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  CMake options
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
if (( $+commands[cmake] ))
then
  export CMAKE_BUILD_PARALLEL_LEVEL=7
fi


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  Golang
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
export GOPATH=$HOME/code/go

#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  PuDB (Python debugger)
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# Set breakpoint() in Python to call pudb
export PYTHONBREAKPOINT="pudb.set_trace"


#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  Libraries
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# export PETSC_DIR=`pwd`
# export PETSC_ARCH=""
# export SLEPC_DIR=~/src/slepc-3.14.2
export DEAL_II_DIR=~/software/dealii-9.3.0/build

#  Intel-MKL {{{
if [[ -s /opt/intel/mkl/bin/mklvars.sh ]]
then
    source /opt/intel/mkl/bin/mklvars.sh intel64
    export MKL_THREADING_LAYER=GNU
fi
#  }}}

# vim: ft=zsh tw=80 ts=2 sw=2
