#!/usr/bin/env zsh

#                                       ███ ██ ███
#                                      ██░ ░░ ░░██
#      ██████ ██████  ██████  █████   ░██   ██ ░██   █████
#     ░░░░██ ░██░░░██░░██░░█ ██░░░██ ██████░██ ░██  ██░░░██
#        ██  ░██  ░██ ░██ ░ ░██  ░██░░░██░ ░██ ░██ ░███████
#       ██   ░██████  ░██   ░██  ░██  ░██  ░██ ░██ ░██░░░░
#  ██  ██████░██░░░   ███   ░░█████   ░██  ░██ ░██ ░░█████
# ░░  ░░░░░░ ░██     ░░░     ░░░░░    ░░   ░░  ░░   ░░░░░
#            ░░

# Executes commands at login pre-zshrc.


# WORDCHARS (non-alphanumeric chars treated as part of a word)
# You can also tweak this if you'd prefer ^w to break on dot, underscore, etc.
export WORDCHARS='*?[]~=&;!#$%^(){}<>'


# WSL
# ========================================================================

# $IS_WSL env. variable existed in the older version in WSL 1, while
# $WSL_DISTRO_NAME variable exists in the current version in WSL 2.
# -n : true if length of string is non-zero.
if [[ -n "$IS_WSL" || -n "$WSL_DISTRO_NAME" ]]; then
  # We are in wsl!
  export WINDOWS_HOST_IP=$(awk '/nameserver/ {print $2}' /etc/resolv.conf)
  export WINDOWS_USER="$(cmd.exe /C "echo %USERNAME%" 2>/dev/null | tr -d '\r')"
else
  # We are not in wsl!
fi

# Paths
# ========================================================================

# Broot {{{
if [[ -s "~/.config/broot/launcher/bash/br" ]]; then
    source ~/.config/broot/launcher/bash/br
fi
# }}}

# Homebrew {{{
if command -v /home/linuxbrew/.linuxbrew/bin/brew > /dev/null 2>&1; then

  local BREWCACHE="$HOME/.cache/Homebrew/brewenv.zsh"

  if [[ ! -s $BREWCACHE(#q.md-7N) ]]
  then
      /home/linuxbrew/.linuxbrew/bin/brew shellenv >! $BREWCACHE 2> /dev/null
  fi
  source $BREWCACHE

  # Enable completion for brew and programs installes with brew.
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

fi
# }}}

# Put Miniconda after Homebrew to make minicondas python be earlier in the $PATH.
# Miniconda {{{

# if is cache load cache
# elsif no cache make cache
# fi

setopt LOCAL_OPTIONS EXTENDED_GLOB GLOB_DOTS

local CONDACACHE="$HOME/.cache/zsh/conda.zsh"

# Существует файл, который был модифицирован в течении 7 последних дней:
# -----  ---------------------------------------------
# (#q…)  glob qualifier
#     .  regular file
#  md-7  was modified within last 7 days
#     N  don't raise an error if nothing will be found
# -----  ---------------------------------------------

# Файл $COONDACACHE существует, был модифицирован не более 7 дней назад
# и он моложе чем файл .zprofile.
if [[ -s $CONDACACHE(#q.md-7N) && $CONDACACHE -nt "$(readlink -- ~/.config/zsh/.zprofile)" ]]
then
    source $CONDACACHE
else
    # Make ~/.cache/zsh folder if it doesn't exist.
    [[ -d ~/.cache/zsh ]] || mkdir -pv ~/.cache/zsh

    local PATH_TO_CONDA_INSTALL="/opt/miniconda3"
    # local PATH_TO_CONDA_INSTALL="$HOME/.miniconda"

    $PATH_TO_CONDA_INSTALL/bin/conda shell.zsh hook >! $CONDACACHE 2> /dev/null

    if [ ! $? -eq 0 ]
    then
        if [ -f "$PATH_TO_CONDA_INSTALL/etc/profile.d/conda.sh" ]
        then
            . "$PATH_TO_CONDA_INSTALL/etc/profile.d/conda.sh"
        else
            export PATH="$PATH_TO_CONDA_INSTALL/bin:$PATH"
        fi
    fi

    source $CONDACACHE

    # # >>> conda initialize >>>
    # __conda_setup="$($PATH_TO_CONDA_INSTALL/bin/conda 'shell.zsh' 'hook' 2> /dev/null)"
    # if [ $? -eq 0 ]; then
    #     eval "$__conda_setup"
    # else
    #     if [ -f "$PATH_TO_CONDA_INSTALL/etc/profile.d/conda.sh" ]; then
    #         . "$PATH_TO_CONDA_INSTALL/etc/profile.d/conda.sh"
    #     else
    #         export PATH="$PATH_TO_CONDA_INSTALL/bin:$PATH"
    #     fi
    # fi
    # unset __conda_setup
    # # <<< conda initialize <<<

fi

# }}}

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# # Set the list of directories that cd searches.
# cdpath=(
#   $HOME/.config
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)


# Zsh
# =====================================================================

# Переменная READNULLCMD определяет команду, которая будет вызвана, если
# перенаправление stdin использовать без ввода команды: `< file.txt`.
READNULLCMD='less'

# Editors
# ========================================================================

# export EDITOR VISUAL
if command -v nvim > /dev/null 2>&1; then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi

export VISUAL="$EDITOR"

export PAGER='less'


# Browser
# ========================================================================
if [[ -f /opt/vivaldi/vivaldi ]]; then
  export BROWSER='/opt/vivaldi/vivaldi'
fi


# Language
# ========================================================================

# if [[ -z "$LANG" ]]; then
#     export LANG='en_US.UTF-8'
#     export LANGUAGE=en_US.UTF-8
# fi


# Man
# ========================================================================

export MANWIDTH=80  # The width of the text column in the man.

# Tie together the scalar $MANPATH and the array $manpath
# in the same way that $PATH and $path ties.
typeset -T MANPATH manpath

# Ensure array do not contain duplicates.
typeset -gU manpath

# # Use `bat` as a colorizing pager for `man`
# export MANPAGER="sh -c 'col -bx | bat -l man -p'"


# Less
# ========================================================================

# Set the default Less options.
# Mouse-wheel scrolling has been disabled  -X and -F (exit if the content fits on one screen) to enable it.

# -F: exit if the content fits on one screen
# -g: Highlights just the current match of any searched string.
# -i: Case-insensitive searches.
# -M: Shows more detailed prompt, including file position.
# -N: Shows line numbers (useful for source code viewing).
# -R or --RAW-CONTROL-CHARS
# -S: Disables line wrap ("chop long lines"). Long lines can be seen by side scrolling.
# -X: Leave file contents on screen when less exits.
# -?: Shows help.
# +F: Follow mode for log.
# -w or --hilite-unread:
#     Temporarily highlights the first "new" line after a forward movement of a full page.
# -z-4: Move page not on the full high of the screen but on high minus 4 lines

# export LESS='-F -i -M -R -S -w -z-3'
export LESS='-F -i -M -R -S -z-3'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

export LESSHISTFILE="$HOME/.cache/lesshst"


# Colored man pages
# ========================================================================

# export LESS_TERMCAP_mb=$'\e[01;31m'     # Begins blinking.
export LESS_TERMCAP_md=$'\e[01;37m'     # Begins bold.
export LESS_TERMCAP_so=$'\e[00;47;30m'  # Begins standout-mode.
export LESS_TERMCAP_us=$'\e[04;97m'     # Begins underline.
export LESS_TERMCAP_me=$'\e[0m'         # Ends mode.
export LESS_TERMCAP_se=$'\e[0m'         # Ends standout-mode.
export LESS_TERMCAP_ue=$'\e[0m'         # Ends underline.


# LS_COLORS
# ========================================================================

# BSD ls colors
export LSCOLORS="Gxfxcxdxbxegedabagacad"

# ----------------
#  Specification:
# ----------------
#
#   LS_COLORS='di=1:fi=0:...:or=31:*.deb=90'
#
# The '*.deb=90' parameter above tells 'ls' to display any files
# ending with a '.deb' extension using the color specified, 90 or dark grey
# in this case. This can be applied to any types of files (eg. you could
# use '*.jpg=33' to make JPEG files appear orange).
#
# The $LS_COLORS variable aldo used to color the zsh comletions.

# Tie together the scalar $LS_COLORS and the array $ls_colors in the same way
# that $PATH and $path ties.
typeset -T LS_COLORS ls_colors

# Here the ';' chars need to be escaped by '\' (for example: di=1\;36), other
# way they somewhy will be converted to ':' chars. Or it is also work to
# enclose them in quotes.
export ls_colors=(
  'di=1;36'   # Directory : bold; cyan
  'fi=0'      # File : default
  'ln=35'     # Symbolic Link : purple
  'pi=33'     # Fifo file
  'so=32'     # Socket file
  'bd=30;46'  # Block (buffered) special file : black; cyan background
  'cd=34;43'  # Character (unbuffered) special file
  # 'or'        # (ORPHAN) Symbolic link pointing to an orphaned non-existent file
  # 'mi'        # Non-existent file pointed to by a symbolic link (visible when you type ls -l)
  'su=30;41'  # File that is setuid (u+s)
  'sg=30;46'  # File that is setgid (g+s)
  'tw=30;42'  # Directory that is sticky and other-writable (+t,o+w)
  'ow=30;43'  # Directory that is other-writable (o+w) and not sticky
  'ex=31'     # File which is executable (ie. has ‘x’ set in permissions).
)


# Bat
# ========================================================================
export BAT_PAGER="less ${LESS}"
# export BAT_PAGER="less -RF"


# Ripgrep
# ========================================================================
export RIPGREP_CONFIG_PATH=$HOME/.config/rg/config

# Par (paragraph formating)
# ========================================================================
# The following string is recommended in par man.
export PARINIT='rTbgqR B=.,?_A_a Q=_s>|'


# XDG
# ========================================================================
# export XDG_RUNTIME_DIR="/tmp/runtime-$USER"

# pkg-config
# ========================================================================

# # Create parameter and array and tie them together in the manner of $PATH
# # and $path.
# typeset -T -gU PKG_CONFIG_PATH pkg_config_path
# export PKG_CONFIG_PATH
#
# pkg_config_path=(
#     /usr/lib/pkgconfig
#     /usr/lib/x86_64-linux-gnu/pkgconfig
#     /usr/share/pkgconfig
#     /opt/petsc-real/lib/pkgconfig
#     /opt/slepc-real/lib/pkgconfig
# )
#

# Intel-MKL
# ========================================================================

if [[ -s /opt/intel/mkl/bin/mklvars.sh ]]; then
    source /opt/intel/mkl/bin/mklvars.sh intel64
    export MKL_THREADING_LAYER=GNU
fi

# PuDB (Python debugger)
# ========================================================================
# Set breakpoint() in Python to call pudb
export PYTHONBREAKPOINT="pudb.set_trace"

# vim: ft=zsh
