#!/usr/bin/env zsh

#                     ██
#                    ░██
#      ██████  ██████░██████   █████  ██████  ██    ██
#     ░░░░██  ██░░░░ ░██░░░██ ██░░░██░██░░░██░██   ░██
#        ██  ░░█████ ░██  ░██░███████░██  ░██░░██ ░██
#       ██    ░░░░░██░██  ░██░██░░░░ ░██  ░██ ░░████
#  ██  ██████ ██████ ░██  ░██░░█████ ░██  ░██  ░░██
# ░░  ░░░░░░ ░░░░░░  ░░   ░░  ░░░░░  ░░   ░░    ░░

# For WSL
[[ "$(umask)" = "000" ]] && umask 022

export ZDOTDIR=~/.config/zsh

# On Ubuntu the `compinit` function is called in '/etc/zshrc', what is not
# really helping.
# https://blog.patshead.com/2011/04/improve-your-oh-my-zsh-startup-time-maybe.html
skip_global_compinit=1

# https://github.com/sorin-ionescu/prezto/blob/master/runcoms/zshenv
# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Home-made scripts
export PATH=$PATH:${HOME}/.bin

# export GIT_CONFIG=~/.config/git/config
