#!/usr/bin/env zsh
#                     ██
#                    ░██
#      ██████  ██████░██████  ██████  █████
#     ░░░░██  ██░░░░ ░██░░░██░░██░░█ ██░░░██
#        ██  ░░█████ ░██  ░██ ░██ ░ ░██  ░░
#       ██    ░░░░░██░██  ░██ ░██   ░██   ██
#  ██  ██████ ██████ ░██  ░██░███   ░░█████
# ░░  ░░░░░░ ░░░░░░  ░░   ░░ ░░░     ░░░░░

# Setting autoloaded functions from my local library {{{
# I load them here because use 'color' function later to style output.
local my_zsh_functions=${ZDOTDIR}/functions
fpath+=($my_zsh_functions)
if [[ -d "$my_zsh_functions" ]]
then
  autoload -Uz $(ls $my_zsh_functions)
fi
# }}}

# (( $+commands[bin] )) || install_missing_programs
install_missing_programs

# Powerlevel10k instant prompt {{{
# --------------------------------
# Enable Powerlevel10k instant prompt. Should stay close to the top of
# ~/.config/zsh/.zshrc.  Initialization code that may require console input
# (password prompts, [y/n] confirmations, etc.) must go above this block,
# everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]
then
  # Suppress the warining about console output during zsh initialization.
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# }}}

# Plugin manager invocation {{{

# 'declare' is the same as 'typeset'.
# -A  - The names refer to associative array parameters.
declare -A ZSH_SNAP
ZSH_SNAP[HOME_DIR]="$HOME/.local/share/znap/zsh-snap"
ZSH_SNAP[PLUGINS_DIR]="$HOME/.local/share/znap"
ZSH_SNAP[BIN]="$ZSH_SNAP[HOME_DIR]/znap.zsh"
ZSH_SNAP[EVAL]=$HOME/.cache/zsh-snap/eval
ZSH_SNAP[FPATH]=$HOME/.cache/zsh-snap/fpath

if [[ ! -s $ZSH_SNAP[BIN] ]]; then
  git clone --depth=1 'https://github.com/marlonrichert/zsh-snap.git' $ZSH_SNAP[HOME_DIR]
fi

source $ZSH_SNAP[BIN]

# Do not auto compile functions in my folder, because
# I compile them later into one library file.
zstyle ':znap:*' auto-compile-ignore "${my_zsh_functions}/*"
# }}}

# Prompt {{{
THEME=powerlevel10k
# THEME=geometry

case $THEME in
  powerlevel10k)
    [[ -f ~/.config/zsh/themes/p10k.zsh ]] &&
      source ~/.config/zsh/themes/p10k.zsh

    znap source romkatv/powerlevel10k
    ;;
  geometry)
    # https://github.com/geometry-zsh/geometry
    GEOMETRY_COLOR_DIR=152

    # GEOMETRY_PROMPT=(geometry_status geometry_path) # redefine left prompt
    # GEOMETRY_RPROMPT+=(geometry_exec_time pwd)      # append exec_time and pwd right prompt

    znap prompt geometry-zsh/geometry
    ;;
esac
unset THEME
# }}}

# Terminal title {{{
# Heavy inspired by: https://github.com/zpm-zsh/title
_show_title()
{
  # print -Pn "\033]0;${PROMPT_TITLE:-"$USER@$HOST"}\007"
  print -Pn "\033]0;${PROMPT_TITLE}\007"
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd _show_title
_show_title

# # PROMPT_TITLE='$USER@$HOST $PWD'  # default
#
# # Полный путь до текущей директории. Подстроку эквивалентную `$HOME`
# # заменяем на тильду. Ковычки дожны быть одинарными. С двойными заголовок
# # не обновляется при смене директории.
# # PROMPT_TITLE='${PWD/#${HOME}/~}'
#
# PROMPT_TITLE=''

# }}}

# Core settings {{{

# 'declare' is the same as 'typeset'.
# -A  - The names refer to associative array parameters.
declare -A ZSH

ZSH[cache]="$HOME/.cache/zsh"
ZSH[completions]="$ZSH[cache]/completions"
ZSH[scripts]="$ZSH[cache]/scripts"

[ -d $ZSH[completions] ] || mkdir -p $ZSH[completions]
[ -d $ZSH[scripts] ] || mkdir -p $ZSH[scripts]


# REPORTTIME=20            # Report time stats of commands running longer
#                          # than 20 sec.

setopt extended_glob     # Because someday i will learn advanced pattern
                         # matching.

                         # In order to use #, ~ and ^ for filename
                         # generation grep word
                         # *~(*.gz|*.bz|*.bz2|*.zip|*.Z) -> searches for
                         # word not in compressed files don't forget to
                         # quote '^', '~' and '#'!

setopt auto_cd           # If a command is issued that can't be executed as
                         # a normal command, and the command is the name of
                         # a directory, perform the cd command to that
                         # directory.

setopt auto_pushd        # Make 'cd' push the old directory onto the
                         # directory stack

setopt pushd_ignore_dups # Don't push multiple copies of the same directory
                         # onto the directory stack.

setopt pushd_silent      # Do not print the directory stack after 'pushd'
                         # or 'popd'.

setopt pushd_minus       # Exchanges the meanings of `+' and `-' when used
                         # with a number to specify a directory in the
                         # stack.

unsetopt cdable_vars     # Нельзя вводить пути для команды 'cd' (или без
                         # неё, если используетя опция 'auto_cd') в
                         # домашней директории без '~/' в начале.

unsetopt clobber         # With this option the `>` redirection, if file
                         # exists, truncates it to zero length.  So unset
                         # it we NOT aLlows `>' redirection to truncate
                         # existing files.  This way `>!' or `>|' must be
                         # used to truncate a file.

setopt interactive_comments  # Allow comments even in interactive shells.

setopt nomatch
# unsetopt nomatch         # DON'T YOU YELL AT ME WHEN YOU CAN'T FIND A MATCH.
#                          # THAT'S YOUR PROBLEM, NOT MINE.

unsetopt beep            # Seriously why does this shit even exist.

setopt combining_chars   # Combine zero-length punctuation characters
                         # (accents) with the base character.

setopt rc_quotes         # Allow 'Henry''s Garage' instead of 'Henry'\''s
                         # Garage'.

setopt hash_list_all     # Whenever a command completion is attempted,
                         # make sure the entire command path is hashed
                         # first.

# Jobs
setopt long_list_jobs    # List jobs in the long format by default.
setopt auto_resume       #   Attempt to resume existing job before creating
# a new process.
setopt notify            # Report status of background jobs immediately.
unsetopt bg_nice         #   Don't run all background jobs at a lower
# priority.
unsetopt hup             # Don't kill jobs on shell exit.
unsetopt check_jobs      # Don't report on jobs when shell exit.

setopt correct_all       # Correct the spelling of all arguments in a line.
CORRECT_IGNORE_FILE='.*'

# Если в слове есть ошибка, предложить исправить её:
SPROMPT="Ошибка! ввести %r вместо %R? ([Y]es/[N]o/[E]dit/[A]bort) "

source $ZDOTDIR/settings/history.zsh

# }}}

# Completions {{{

source $ZDOTDIR/settings/completion.zsh

fpath+=(
  $ZSH[completions]
  # ~[zsh-users/zsh-completions]/src
)

znap install zsh-users/zsh-completions

github_completion exa 'https://github.com/ogham/exa/blob/master/completions/zsh/_exa'
github_completion vifm 'https://github.com/vifm/vifm/blob/master/data/shell-completion/zsh/_vifm'
github_completion cppman 'https://github.com/aitjcize/cppman/blob/master/misc/completions/cppman.zsh'

# conda completion {{{
znap install esc/conda-zsh-completion

# zstyle ":conda_zsh_completion:*" use-groups true

# # Display unnamed environments and prefixes of environments.
# zstyle ":conda_zsh_completion:*" show-unnamed true

# # display environments autocompletion sorted in creation order
# zstyle ":conda_zsh_completion:*" sort-envs-by-time true

# }}}

znap eval pip-completion "pip completion --zsh"

if (( $+commands[pipx] )) && (( $+commands[register-python-argcomplete3] )); then
  znap eval pipx-completion "register-python-argcomplete3 pipx"
fi

compdef _gnu_generic update-alternatives

# zinit snippet OMZ::plugins/fd/_fd

# zoxide completions {{{
_zoxide_zsh_tab_completion()
{
    (( $+compstate )) && compstate[insert]=menu
    local keyword="${words:2}"
    local completions=(${(@f)"$(zoxide query -l "$keyword")"})

    if [[ ${#completions[@]} == 0 ]]; then
        _files -/
    else
        compadd -U -V z "${(@)completions}"
    fi
}
# }}}

if (( $+functions[compdef] )); then
    compdef _zoxide_zsh_tab_completion z 2> /dev/null
fi

# }}}

# Expand aliaces                                                        {{{
#――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# Define three types of aliaces:
# alias  - will be expanded into full command with wightspace after
# balias - will be expanded without wightspace after
# ialias - won't be expanded
#
# -------------------------------------------------------
# https://blog.sebastian-daschner.com/entries/zsh-aliases
#――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

# Blank aliases
typeset -a baliases
baliases=()

balias() # {{{
{
  alias $@
  args="$@"
  args=${args%%\=*}
  baliases+=(${args##* })
} # }}}

# Ignored aliases
typeset -a ialiases
ialiases=()

ialias() # {{{
{
  alias $@
  args="$@"
  args=${args%%\=*}
  ialiases+=(${args##* })
} # }}}

# Functionality
expand-alias-space() # {{{
{
  [[ $LBUFFER =~ "\<(${(j:|:)baliases})\$" ]]; insertBlank=$?
  if [[ ! $LBUFFER =~ "\<(${(j:|:)ialiases})\$" ]]
  then
    zle _expand_alias
  fi
  zle self-insert
  if [[ "$insertBlank" = "0" ]]
  then
    zle backward-delete-char
  fi
} # }}}
zle -N expand-alias-space

# Expand aliaces on space
bindkey " " expand-alias-space
bindkey -M isearch " " magic-space
#―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――}}}

# Plugins and programs {{{

# zsh-autosuggestions {{{
znap source zsh-users/zsh-autosuggestions

export ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)
export ZSH_AUTOSUGGEST_USE_ASYNC=1  # suggestions will be fetched asynchronously

# Speed up pasting w/ autosuggest
# https://github.com/zsh-users/zsh-autosuggestions/issues/238
pasteinit()
{
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic
}

pastefinish()
{
  zle -N self-insert $OLD_SELF_INSERT
}

zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish

# Clear suggestions on paste
# https://github.com/zsh-users/zsh-autosuggestions/issues/351
ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(bracketed-paste)

# }}}

# znap source changyuheng/zsh-interactive-cd

# mcfly {{{
if (( $+commands[mcfly] ))
then
  export HISTFILE=$HOME/.cache/zsh/zsh_history
  export MCFLY_KEY_SCHEME=vim
  export MCFLY_FUZZY=true
  export MCFLY_RESULTS=30
  znap eval mcfly 'mcfly init zsh'
fi
# }}}

# fzf {{{

#――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――#
# fzf keybindings for Zsh                                                #
# -----------------------                                                #
# CTRL-R - Paste the selected command from history into the command line #
# CTRL-T - Paste the selected file path(s) into the command line         #
# ALT-C  - cd into the selected directory                                #
#                                                                        #
# fzf completion for Zsh                                                 #
# ----------------------                                                 #
# Fuzzy completion for files and directories can be triggered if the     #
# word before the cursor ends with the trigger sequence which is by      #
# default **.                                                            #
#                                                                        #
# fzf-marks                                                              #
# ---------                                                              #
# mark <name> - register a new mark to the current directory             #
# CTRL-F - fzf-marks                                                     #
#――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――#

# znap source junegunn/fzf shell/key-bindings.zsh

# fzf keybindings
gitfile $ZSH[scripts]/fzf-key-bindings.zsh 'https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh'
source $ZSH[scripts]/fzf-key-bindings.zsh

# # use fzf for completion
# gitfile $ZSH[scripts]/fzf-completion.zsh 'https://github.com/junegunn/fzf/blob/master/shell/completion.zsh'
# source $ZSH[scripts]/fzf-completion.zsh

# fzf man
gitfile $HOME/.local/share/man/man1/fzf.1 'https://github.com/junegunn/fzf/blob/master/man/man1/fzf.1'

# # fzf-marks {{{
# gitfile $ZSH[scripts]/fzf-marks.zsh 'https://github.com/urbainvaes/fzf-marks/blob/master/fzf-marks.plugin.zsh'
# source $ZSH[scripts]/fzf-marks.zsh
#
# export FZF_MARKS_FILE="${HOME}/.cache/zsh/fzf-marks"
#
# export FZF_MARKS_JUMP='^f'  # Ctrl-f
# bindkey ${FZF_MARKS_JUMP:-'^g'} fzm
# # }}}

# # fzf.vim  Needed to enable fzf in vim/neovim.
# zinit ice wait"2" lucid id-as"auto" as"null"
# zinit snippet https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim

export FZF_DEFAULT_OPTS='--height 75% --layout=reverse --border'
# export FZF_DEFAULT_OPTS='--height 75% --layout=reverse --border --preview="head -30 {}"'

# Using ripgrep with fzf.
# (I've tried fd, but ripgrep is faster.)
# -------------------------------------------------------------------
# --files: List files that would be searched but do not search.
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders.
# --follow: Follow symlinks.
# -g or --glob: Additional conditions for search (in this case ignore
#               everything in the .git/ folder).
# -------------------------------------------------------------------
# export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"


# Using bfs utility for directory searching.
# https://github.com/tavianator/bfs
if (( $+commands[bfs] ))
then
  # # don't show hidden folders
  # export FZF_ALT_C_COMMAND="bfs -type d -nohidden -L -print 2> /dev/null"

  # show hidden folders
  export FZF_ALT_C_COMMAND="bfs -type d -L -print 2> /dev/null"
else
  print $(color Yellow 'Warning:') $(color White 'fzf') use $(color White 'bfs') utility but it is $(color Red 'not installed\!')
  print $(color White "https://github.com/tavianator/bfs")
fi

# Make fzf history search unique {{{
fzf-history-widget()
{
  local selected num
  setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
  selected=( $(fc -rl 1 | perl -ne 'print if !$seen{(/^\s*[0-9]+\s+(.*)/, $1)}++' |
    sort -k2 -k1rn | uniq -f 1 | sort -r -n |
    FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS --query=${(qqq)LBUFFER} +m" $(__fzfcmd)) )
  local ret=$?
  if [ -n "$selected" ]
  then
    num=$selected[1]
    if [ -n "$num" ]
    then
      zle vi-fetch-history -n $num
    fi
  fi
  zle reset-prompt
  return $ret
}
# }}}

# Custom CTRL-T command {{{

# Make CTRL-T command return full path to the file, not relevant to $PWD.
# Also if this path is inside the $HOME directory the $HOME prefix exchange
# to tilda `~` symbol.
fzf-file-widget() {

  # If $PWD is not root ('/') add '/' char to make path valid.
  if [ ${PWD} = '/' ]
  then
    local fzf_full_path="/$(__fsel)"
  else
    local fzf_full_path="${PWD}/$(__fsel)"
  fi

  # Exchange the substring at the beginning of the $fzf_full_path
  # variable equal to ${HOME} with '~' symbol.
  fzf_full_path="${fzf_full_path/#${HOME}/~}"

  LBUFFER="${LBUFFER}${fzf_full_path}"

  local ret=$?
  zle reset-prompt
  return $ret
}
# }}}

# }}}

# zoxide {{{
if (( $+commands[zoxide] )); then
  _ZO_ECHO=1
  znap eval zoxide 'zoxide init zsh'
fi
# }}}

# # broot {{{
# if [[ -s "~/.config/broot/launcher/bash/br" ]]
# then
#     source ~/.config/broot/launcher/bash/br
# fi
# # }}}

# conda {{{
local -A CONDA
CONDA[home]="/opt/miniconda3"
CONDA[version]=$($CONDA[home]/bin/conda --version)

znap eval conda "${CONDA[home]}/bin/conda shell.zsh hook  # $CONDA[version]"
# }}}

# vim mode {{{
znap source jeffreytse/zsh-vi-mode
# znap source softmoth/zsh-vim-mode

ZVM_VI_SURROUND_BINDKEY=classic

# cursor {{{

# ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_UNDERLINE
ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_BLOCK

ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_UNDERLINE
# ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLOCK

# }}}

zvm_after_init_commands+=(
  # <C-R> - fussy search in history with mcfly.
  "zvm_bindkey viins '^R' mcfly-history-widget"
)
# }}}

# vifm
# znap install cirala/vifmimg  # Image previews using Überzug for Vifm
znap install anuvyklack/vifmimg  # Image previews using Überzug for Vifm
ialias vifm="vifmrun ."

# znap source ohmyzsh/ohmyzsh plugins/universalarchive
# github_completion universalarchive \
#   'https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/universalarchive/_universalarchive'

#――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
#  WARNING: This two plugins should be last in this order!
#――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
znap source zsh-users/zsh-syntax-highlighting

znap source zsh-users/zsh-history-substring-search
#――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
# }}}

# Functions {{{

# Bash 'help' function analog {{{

# unalias run-help
autoload run-help

# HELPDIR=/usr/share/zsh/"${ZSH_VERSION}"/help
HELPDIR=/usr/share/zsh/help  # in Pop_OS
# }}}

run_ranger() # {{{
{
  zle .reset-prompt
  # BUFFER=" source ranger && clear -x"
  BUFFER=" source ranger"
  zle accept-line
}
zle -N run_ranger
# }}}

# }}}

# Key bindings {{{

# Use backtick for accept zsh-autosuggestions
bindkey \` autosuggest-accept

bindkey "^K" history-substring-search-up
bindkey "^J" history-substring-search-down

# show man page of current command with alt+h
bindkey '\eh' run-help

# Gets the n-th argument from the last command
# by pressing Alt+1, Alt+2, ... Alt+5.
bindkey -s '\e1' "!:0-0 \t"
bindkey -s '\e2' "!:1-1 \t"
bindkey -s '\e3' "!:2-2 \t"
bindkey -s '\e4' "!:3-3 \t"
bindkey -s '\e5' "!:4-4 \t"

# <C-O> - Launch Ranger and cd to the last directory after closing it.
bindkey '^O' run_ranger

# <C-R> - Fussy search in history with mcfly.
bindkey '^R' mcfly-history-widget

# }}}

# Aliaces {{{

# Filesystem aliases
alias ..=' cd ..'
alias ...=' cd ../..'
alias ....=' cd ../../..'
alias .....=' cd ../../../..'

ialias :q='exit'

ialias -g L='| less'

ialias cls='clear'      # clear the screen

ialias help='run-help'  # Bash 'help' function analog.

ialias ping='ping -c 1' # Пингуем один раз вместо бесконечности.

ialias tree='tree -I .git -I .github'

ialias mv='nocorrect mv -v'
ialias cp='nocorrect cp -vR'  # рекурсивное копирование
ialias rm='nocorrect rm -v'
ialias grep='grep --color=auto'
ialias wget='wget -c'  # автоматическое продолжение при разрыве соединения

# Создание каталогов без коррекции и со всеми
# родительскими каталогами, если они отсутствуют.
ialias mkdir='nocorrect mkdir -vp'

# Вывод свободного и использованного дискового пространства в
# "гуманистическом" представлении.
ialias df='df -h'
ialias du='du -h'

if (( $+commands[exa] )); then
  # -F / --classify
  # --no-user
  # --no-time
  # --icons
  # --color=always
  alias ls='exa -F --group-directories-first'
  alias ll='exa -lF --group-directories-first --git'
else
  alias ls='ls --color=auto --group-directories-first'
fi

# Use neovim for vim if present.
if (( $+commands[nvim] )); then
  ialias vim="nvim"
  ialias vimdiff="nvim -d"
  ialias neovide="neovide --multiGrid --geometry=340x120"
fi

# In Debian and its derivatives in package ‘fd-find’ the executable
# and the associated manpage were renamed from ‘fd’ to ‘fdfind’.
if [[ $(grep -Es '^ID_LIKE=.*(?:ubuntu|debian)' /etc/os-release) ]]
then
  ialias fd=fdfind
fi

# Git
alias gs='git status'
alias gc='git checkout'
alias gd='git diff'
alias -g random='-m curl -s http://whatthecommit.com/index.txt'

# Lists the ten most used commands.
ialias history-stat="history 0 | awk '{print \$2}' | sort | uniq -c | sort -n -r | head"

# }}}

unset my_zsh_functions

# vim: tw=75 ts=2 sw=2 fdm=marker
