;;; init.el --- Emacs main configuration file -*- lexical-binding: t; buffer-read-only: t; no-byte-compile: t -*-
;;;
;;; Commentary:
;;; This file was automatically generated by `org-babel-tangle'.
;;; Do not change this file.  Main config is located in ~/.config/emacs/README.org
;;;
;;; Code:

(defvar elpaca-installer-version 0.4)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil
                              :files (:defaults (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (call-process "git" nil buffer t "clone"
                                       (plist-get order :repo) repo)))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (kill-buffer buffer)
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

(elpaca elpaca-use-package
        (elpaca-use-package-mode))

(elpaca-wait)

(with-eval-after-load 'evil
  (with-eval-after-load 'elpaca-ui   (evil-make-intercept-map elpaca-ui-mode-map))
  (with-eval-after-load 'elpaca-info (evil-make-intercept-map elpaca-info-mode-map)))

(use-package s    :elpaca t) ;; string manipulation library
(use-package dash :elpaca t) ;; list manipulation library
(use-package diminish :elpaca t)
(use-package hydra :elpaca t)

(use-package use-package
  :no-require
  :custom (use-package-enable-imenu-support t))

(use-package general
  :elpaca t
  :config (general-auto-unbind-keys))

(define-prefix-command 'leader-map)
(define-prefix-command 'semicolon-leader-map)
(define-prefix-command 'my/orgmode-leader-map)
(define-prefix-command 'my/notes-map)
(define-prefix-command 'my/bookmark-map)

(defun my/append-to-list (list-var elements)
  "Append ELEMENTS to the end of LIST-VAR.

The return value is the new value of LIST-VAR."
  (unless (consp elements)
    (error "ELEMENTS must be a list"))
  (let ((list (symbol-value list-var)))
    (if list
        (setcdr (last list) elements)
      (set list-var elements)))
  (symbol-value list-var))

(defun my/dired-xdg-open ()
  "In a dired buffer, open file or folder on the current line with `xdg-open'
shell command."
  (interactive)
  (let* ((file (dired-get-filename nil t)))
    (call-process "xdg-open" nil 0 nil file)))

(defun my/paste-and-indent-after ()
  (interactive)
  (with-undo-amagamate ;; emacs 29
   (evil-paste-after 1)
   (evil-indent (evil-get-marker ?\[) (evil-get-marker ?\]))))

(defun my/paste-and-indent-before ()
  (interactive)
  (with-undo-amagamate ;; emacs 29
   (evil-paste-before 1)
   (evil-indent (evil-get-marker ?\[) (evil-get-marker ?\]))))

(use-package better-defaults :elpaca t)
(use-package emacs
  :after better-defaults
  :custom
  (user-full-name "Yuriy Artemyev")
  (user-mail-address "anuvyklack@gmail.com")
  (ring-bell-function #'ignore)
  (inhibit-startup-message t)
  (cursor-type 'box)
  (cursor-in-non-selected-windows nil)
  (require-final-newline t)
  (truncate-lines t)
  (fill-column 80)
  (comment-empty-lines t)
  (help-window-select t)
  (help-at-pt-display-when-idle t)
  (what-cursor-show-names t)
  (sentence-end-double-space nil)
  (scroll-conservatively 101)
  (scroll-margin 0)
  ;; (auto-window-vscroll nil)
  (scroll-error-top-bottom nil)
  (use-short-answers t)
  :config
  ;; (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (horizontal-scroll-bar-mode -1)
  (blink-cursor-mode 0)
  (set-fringe-mode 3)
  (column-number-mode 1))

(when window-system
  (set-face-attribute 'default nil :font "Inconsolata LGC" :height 125)
  ;; (set-face-attribute 'default nil :font "Roboto Mono" :height 125)
  ;; (set-face-attribute 'default nil :font "Monego" :height 125)
  (set-fontset-font t '(?\xf0001 . ?\xf1af0) "Symbols Nerd Font Mono" nil 'prepend)
  ;; (set-fontset-font t ?\xe876 "Material Design Icons" nil 'prepend)
  ;; (set-fontset-font t ? "Material Design Icons" nil 'prepend)
  ;; (set-fontset-font t ? "Material Design Icons Desktop" nil 'prepend)
  (set-fontset-font t '(?\x1fb00 . ?\x1fbca) "LegacyComputing" nil 'prepend)
  ;; (set-fontset-font t 'latin "Noto Sans")
  ;; (set-fontset-font t '(?\xea60 . ?\xec11) "codicon" nil 'prepend)
  
  ;; (set-fontset-font t '(? . ?) "codicon")
  
  ;; (let ((fontset (face-attribute 'default :fontset)))
  ;;   (set-fontset-font fontset '(?\xea60 . ?\xec11) "codicon" nil 'append))
  
  ;; (set-fontset-font (frame-parameter nil 'font)
  ;;                   '(?\xea60 . ?\xec11)
  ;;                   (font-spec :family "codicon"
  ;;                              :weight nil
  ;;                              :size nil)
  ;;                   nil
  ;;                   'prepend)
  (set-frame-size (selected-frame) 134 63)
  (set-frame-position (selected-frame) 1190 35))

(set-frame-size (selected-frame) 134 63)
(set-frame-position (selected-frame) 1190 35)

(setq-default custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file))

(use-package display-line-numbers
  :custom
  ;; (display-line-numbers-width 4)
  (display-line-numbers-grow-only t)
  (display-line-numbers-width-start t)
  :hook (prog-mode . display-line-numbers-mode))

(use-package display-fill-column-indicator
  :hook (prog-mode . display-fill-column-indicator-mode))

(use-package elec-pair
  :config
  (electric-pair-mode)
  :hook
  (org-mode . (lambda ()
                (setq-local electric-pair-inhibit-predicate
                            (lambda (c)
                              (if (char-equal c ?<)
                                  t
                                (electric-pair-default-inhibit c)))))))

(use-package delsel
  :config
  (delete-selection-mode))

(use-package mwheel
  :custom
  (mouse-wheel-tilt-scroll t)
  (mouse-wheel-progressive-speed nil))

(use-package isearch
  :custom
  (isearch-lazy-count t)
  (isearch-lazy-highlight t))

(use-package outline
  :custom
  (outline-minor-mode-cycle t))

(use-package tab-bar
  :config (tab-bar-mode 1))

(use-package info
  :config
  (add-to-list 'Info-directory-list
               (expand-file-name ".nix-profile/share/info" (getenv "HOME"))))

(use-package vertico
  :elpaca t
  :custom
  (vertico-count 14) ;; How many candidates to show.
  (vertico-scroll-margin 2)
  (vertico-cycle nil)
  ;; Grow and shrink the Vertico minibuffer
  ;; (setq vertico-resize t)
  ;; (read-extended-command-predicate #'command-completion-default-include-p)
  (enable-recursive-minibuffers t)
  (minibuffer-depth-indicate-mode t)
  (read-file-name-completion-ignore-case t)
  (read-buffer-completion-ignore-case t)
  (completion-ignore-case t)
  :bind (:map minibuffer-local-map
         ("C-h" . backward-kill-word))
  :init
  (ido-mode -1)
  (vertico-mode)
  :config
  (defun my/crm-indicator (args)
    "Add prompt indicator to `completing-read-multiple'.
  We display [CRM<separator>], e.g., [CRM,] if the separator is a comma."
    (cons (format "[CRM%s] %s"
                  (replace-regexp-in-string
                   "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
                   crm-separator)
                  (car args))
          (cdr args)))
  
  (advice-add #'completing-read-multiple :filter-args #'my/crm-indicator)
  (setq minibuffer-prompt-properties '(read-only t
                                       cursor-intangible t
                                       face minibuffer-prompt))
  (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)
  (add-to-list 'load-path (expand-file-name "elpaca/repos/vertico/extensions"
                                            user-emacs-directory))
  (use-package vertico-repeat
    :config
    (keymap-global-set "M-r" #'vertico-repeat)
    (add-hook 'minibuffer-setup-hook #'vertico-repeat-save)))

(use-package orderless
  :elpaca t
  :after vertico
  :custom
  (completion-styles '(orderless basic))
  ;; (completion-styles '(substring orderless))
  ;; (completion-styles '(flex)) ;; fussy search
  (orderless-component-separator #'orderless-escapable-split-on-space)
  (orderless-matching-styles '(orderless-initialism
                               orderless-prefixes
                               orderless-regexp)))

(use-package consult
  :elpaca t
  :init
  (setq completion-in-region-function #'consult-completion-in-region))

(use-package consult-dir
  :elpaca t
  :bind ("C-x C-d" . consult-dir))

(use-package marginalia
  :elpaca t
  :custom
  (marginalia-annotators '(marginalia-annotators-heavy
                           marginalia-annotators-light
                           nil))
  ;; (marginalia-field-width 100)
  :init (marginalia-mode)
  :config
  (general-def :keymaps 'minibuffer-local-map
    :states '(motion insert)
    "M-a" 'marginalia-cycle))

(use-package all-the-icons-completion
  :elpaca t
  :after (marginalia all-the-icons)
  :hook (marginalia-mode . all-the-icons-completion-marginalia-setup)
  :init
  (all-the-icons-completion-mode))

(use-package embark
  :elpaca t
  :config
  (general-def
    :states 'motion
    "," 'embark-act
    "M-," 'embark-dwim)
  ;; Show the Embark target at point via Eldoc.  You may adjust the Eldoc
  ;; strategy, if you want to see the documentation from multiple providers.
  (add-hook 'eldoc-documentation-functions #'embark-eldoc-first-target)
  ;; (setq eldoc-documentation-strategy #'eldoc-documentation-compose-eagerly)
  )

(use-package embark-consult
  :elpaca t
  :hook
  (embark-collect-mode . consult-preview-at-point-mode))

(use-package corfu
  :elpaca t
  :init
  (global-corfu-mode)
  :custom
  ;; (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
  (corfu-auto t)                 ;; Enable auto completion
  (corfu-separator ?\s)          ;; Orderless field separator
  (corfu-auto-prefix 3)
  ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
  ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
  ;; (corfu-preview-current nil)    ;; Disable current candidate preview
  ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
  ;; (corfu-on-exact-match nil)     ;; Configure handling of exact matches
  ;; (corfu-scroll-margin 5)        ;; Use scroll margin  :init
  (completion-cycle-threshold 3)
  ;; (read-extended-command-predicate #'command-completion-default-include-p)
  (tab-always-indent 'complete)
  :config
  (defun corfu-enable-in-minibuffer ()
    "Enable Corfu in the minibuffer if `completion-at-point' is bound."
    (when (where-is-internal #'completion-at-point
                             (list (current-local-map)))
      (setq-local corfu-auto t ;; Enable/disable auto completion
                  corfu-echo-delay t ;; Disable automatic echo and popup
                  corfu-auto-prefix 2
                  corfu-popupinfo-delay nil)
      (corfu-mode 1)))
  
  (add-hook 'minibuffer-setup-hook #'corfu-enable-in-minibuffer)
  (defun corfu-enable-always-in-minibuffer ()
    "Enable Corfu in the minibuffer if Vertico are not active."
    (unless (or (bound-and-true-p vertico--input)
                (eq (current-local-map) read-passwd-map))
      (setq-local corfu-auto t ;; Enable/disable auto completion
                  corfu-echo-delay t ;; Disable automatic echo and popup
                  corfu-auto-prefix 2
                  corfu-popupinfo-delay nil)
      (corfu-mode 1)))
  
  (add-hook 'minibuffer-setup-hook #'corfu-enable-always-in-minibuffer 1))

(use-package cape
  :elpaca t
  ;; Bind dedicated completion commands
  ;; Alternative prefix keys: C-c p, M-p, M-+, ...
  :bind (("C-c p p" . completion-at-point) ;; capf
         ("C-c p t" . complete-tag)        ;; etags
         ("C-c p d" . cape-dabbrev)        ;; or dabbrev-completion
         ("C-c p h" . cape-history)
         ("C-c p f" . cape-file)
         ("C-c p k" . cape-keyword)
         ("C-c p s" . cape-symbol)
         ("C-c p a" . cape-abbrev)
         ("C-c p l" . cape-line)
         ("C-c p w" . cape-dict)
         ("C-c p \\" . cape-tex)
         ("C-c p _" . cape-tex)
         ("C-c p ^" . cape-tex)
         ("C-c p &" . cape-sgml)
         ("C-c p r" . cape-rfc1345))
  :init
  ;; Add `completion-at-point-functions', used by `completion-at-point'.
  ;; NOTE: The order matters!
  (add-to-list 'completion-at-point-functions #'cape-dabbrev)
  (add-to-list 'completion-at-point-functions #'cape-file)
  (add-to-list 'completion-at-point-functions #'cape-elisp-block)
  ;;(add-to-list 'completion-at-point-functions #'cape-history)
  ;;(add-to-list 'completion-at-point-functions #'cape-keyword)
  ;;(add-to-list 'completion-at-point-functions #'cape-tex)
  ;;(add-to-list 'completion-at-point-functions #'cape-sgml)
  ;;(add-to-list 'completion-at-point-functions #'cape-rfc1345)
  ;;(add-to-list 'completion-at-point-functions #'cape-abbrev)
  ;;(add-to-list 'completion-at-point-functions #'cape-dict)
  ;;(add-to-list 'completion-at-point-functions #'cape-symbol)
  ;;(add-to-list 'completion-at-point-functions #'cape-line)
)

(use-package lsp-mode
  :elpaca t
  :init
  :hook (;; (python-mode . lsp)
         (lsp-mode . lsp-enable-which-key-integration))
  :commands lsp)

(use-package lsp-ui :elpaca t :commands lsp-ui-mode)
;; (use-package lsp-treemacs :elpaca t :commands lsp-treemacs-errors-list)

(use-package puni
  :disabled
  :elpaca t
  :defer t
  :hook
  (term-mode . puni-disable-puni-mode)
  :init
  ;; The autoloads of Puni are set up so you can enable `puni-mode` or
  ;; `puni-global-mode` before `puni` is actually loaded. Only after you press
  ;; any key that calls Puni commands, it's loaded.
  (puni-global-mode))

(use-package lispy
  :elpaca t
  :custom
  (lispy-safe-delete t)
  (lispy-safe-copy t)
  (lispy-safe-paste t)
  :hook (emacs-lisp-mode . lispy-mode))

(use-package lispyville
  :elpaca t
  :after general
  :hook (lispy-mode . my/lispyville-mode)
  :config
  (lispyville-set-key-theme
   '(operators c-w c-u prettify additional-motions additional wrap))
  (defun my/lispyville-mode ()
    (lispyville-mode)
    (general-def
      :keymaps 'local
      :states 'normal
      "(" 'lispyville-backward-up-list
      "g c" 'lispyville-comment-or-uncomment
      "[ SPC" 'evil-collection-unimpaired-insert-newline-above
      "] SPC" 'evil-collection-unimpaired-insert-newline-below)
    (general-def
      :keymaps 'local
      :states '(motion normal visual)
      ";" '(:keymap semicolon-leader-map)
      ;; ";" '(:keymap evilem-map)
      )
    (general-def
      :keymaps 'local
      :states 'visual
      "g c" 'lispyville-comment-or-uncomment)))

(use-package which-key
  :elpaca t
  :diminish which-key-mode
  :custom
  (which-key-idle-delay 1.2)
  (which-key-popup-type 'side-window)
  :init
  (which-key-mode))

(use-package avy
  :elpaca t
  :custom
  (avy-background t)
  (avy-keys (number-sequence ?a ?z)) ;; Any lower-case letter a-z.
  (avy-style 'at-full)
  (avy-all-windows nil)
  (avy-words)
  :config
  (set-face-attribute 'avy-lead-face nil :foreground "red" :background nil :weight 'bold)
  (set-face-attribute 'avy-lead-face-0 nil :foreground "brown" :background nil) ;:weight 'bold
  ;; (set-face-attribute 'avy-lead-face-1 nil :background "green" :foreground "yellow")
  ;; (set-face-attribute 'avy-lead-face-2 nil :background "green" :foreground "yellow")
  )

(use-package expand-region
  :elpaca t
  :after evil-collection
  :custom
  (expand-region-contract-fast-key "C-v")
  :config
  (general-def
    :states 'visual
    "v" 'er/expand-region))

(use-package magit
  :elpaca t
  :custom
  (evil-collection-magit-use-z-for-folds t) ;; use Z for stash instead
  (evil-collection-magit-use-$-for-end-of-line nil)) ;; use $ for `magit-process-buffer'

(use-package zoxide
  :elpaca t
  :bind (:map leader-map
         ("fz" . zoxide-find-file)))

(use-package gcmh
  :elpaca t
  :diminish
  :config (gcmh-mode 1))

(use-package no-littering
  :elpaca t
  :demand t
  :config
  (when (fboundp 'startup-redirect-eln-cache)
    (startup-redirect-eln-cache
      (convert-standard-filename
        (expand-file-name  "var/eln-cache/" user-emacs-directory)))))

(use-package recentf
  :after no-littering
  :custom
  (recentf-max-menu-items 100)
  (recentf-max-saved-items 100)
  :config
  (recentf-mode 1)
  ;; ;; Save recentf list into file every 10 minutes.
  ;; (run-at-time nil 600 'recentf-save-list)
  )

(use-package savehist
  :after no-littering
  ;; :custom
  ;; (savehist-additional-variables '(register-alist))
  :config
  (savehist-mode)
  (setq savehist-additional-variables '(register-alist)))

(use-package projectile
  :elpaca t
  ;; :custom
  ;; (projectile-auto-discover t)
  ;; (projectile-project-search-path)
  :config
  (projectile-mode)
  (general-def :keymaps 'projectile-command-map
    "B" 'projectile-ibuffer)
  (keymap-unset projectile-command-map "I" t))

(use-package consult-projectile
  :elpaca t
  ;; :straight (consult-projectile
  ;;            :type git :host gitlab
  ;;            :repo "OlMon/consult-projectile" :branch "master")
  :bind (([remap projectile-switch-to-buffer] . consult-projectile-switch-to-buffer)
         ([remap projectile-find-dir] . consult-projectile-find-dir)
         ([remap projectile-find-file] . consult-projectile-find-file)
         ([remap projectile-recentf] . consult-projectile-recentf)
         ;; ([remap projectile-switch-project] . consult-projectile-switch-project)
         ([remap projectile-switch-project] . consult-projectile)
         ))

(use-package helpful
  :elpaca t
  ;; :preface
  ;; (add-to-list 'load-path "~/code/emacs/helpful")
  :bind (([remap describe-function] . helpful-callable)
         ([remap describe-variable] . helpful-variable)
         ([remap describe-command] . helpful-command)
         ([remap describe-key] . helpful-key)
         :map help-map
         ("F" . helpful-function)))

(use-package rainbow-delimiters
  :elpaca t
  :hook (prog-mode . rainbow-delimiters-mode))

(use-package rg
  :elpaca t)

(use-package easy-escape
  :elpaca t
  :hook (emacs-lisp-mode . easy-escape-minor-mode)
  ;; :config
  ;; (add-hook 'emacs-lisp-mode-hook 'easy-escape-minor-mode)
  )

(use-package far
  :elpaca (:host github :repo "eshrh/far.el"))

(use-package flyspell-correct
  :elpaca t
  :hook ((markdown-mode . flyspell-mode)
         ;; (text-mode . flyspell-mode)
         ))

(use-package flyspell-correct-popup
  :elpaca t
  :after flyspell-correct)

(use-package vundo
  :elpaca (:host github :repo "casouri/vundo")
  :custom
  (vundo-glyph-alist vundo-unicode-symbols)
  ;; (vundo-roll-back-on-quit nil)
  (vundo-compact-display nil)
  :config
  (general-def
    ;; :keymaps 'leader-map
    :states 'normal
    "U" 'vundo))

(use-package anzu
  :elpaca t
  :config
  (global-anzu-mode))

(use-package dired
  :custom
  (dired-listing-switches "-lahF -v --group-directories-first")
  (dired-kill-when-opening-new-dired-buffer t)
  (dired-no-confirm t)
  (dired-recursive-deletes 'always)
  (dired-recursive-copies 'always)
  (delete-by-moving-to-trash t)
  (dired-dwim-target t)
  (dired-omit-files "\\`[.]?#\\|\\`[.][.]?\\'\\|\\`[.].+")
  :hook
  (dired-mode . dired-omit-mode)
  (dired-mode . dired-hide-details-mode)
  (dired-mode . hl-line-mode))

(use-package dired-ranger  :elpaca t)
(use-package dired-subtree :elpaca t)
(use-package dired-narrow  :elpaca t)
(use-package dired-open    :elpaca t)
(use-package dired-toggle-sudo :elpaca t)

(use-package wdired
  ;; :custom (wdired-allow-to-change-permissions t)
  )

(use-package dired-collapse
  :elpaca t
  ;; :hook (dired-mode . dired-collapse-mode)
  )

(use-package dired-rainbow
  :elpaca t
  :config
  (dired-rainbow-define html "#4e9a06" ("htm" "html" "xhtml"))
  (defconst my-video-files-extensions
    '("mp3" "mp4" "MP3" "MP4" "avi" "mpg" "flv" "ogg" "mkv")
    "Media files.")
  (dired-rainbow-define media "#ce5c00" my-video-files-extensions)
  ;; Highlight executable files, but not directories:
  (dired-rainbow-define-chmod executable-unix "#4e9a06" "-.*x.*"))

(use-package diredfl ;; Addtional syntax highlighting for dired
  :elpaca t
  :hook ((dired-mode . diredfl-mode)
         (dirvish-directory-view-mode . diredfl-mode))
  ;; :config
  ;; (set-face-attribute 'diredfl-dir-name nil :bold t)
  )

(use-package mu4e
  :preface
  (add-to-list 'load-path "~/.nix-profile/share/emacs/site-lisp/mu4e")
  ;; :defer 20 ; Wait until 20 seconds after startup
  :custom
  (mail-user-agent 'mu4e-user-agent)
  ;; (mu4e-headers-date-format "%Y/%m/%d")
  (mu4e-change-filenames-when-moving t)
  (mu4e-bookmarks
   `((:name "Inbox"
            ;; :query ,(string-join '("maildir:\"/anuvyklack@gmail/[Gmail]/Вся почта\""
            ;;                        "AND NOT maildir:/anuvyklack@gmail/Архив") " ")
            :query ,(concat "maildir:\"/anuvyklack@gmail/[Gmail]/Вся почта\" "
                            "AND NOT maildir:/anuvyklack@gmail/Архив "
                            "AND NOT flag:list ")
            :key ?i
            :favorite t)
     (:name "Mail lists"
            :query ,(concat "flag:list "
                            "AND maildir:\"/anuvyklack@gmail/[Gmail]/Вся почта\" ")
            ;; :query ,(concat "flag:list "
            ;;                 "AND NOT maildir:/anuvyklack@gmail/[Gmail]/Корзина "
            ;;                 "AND NOT maildir:/anuvyklack@gmail/[Gmail]/Спам")
            :key ?l)
     ;; (:name "Unread messages" :query "flag:unread AND NOT flag:trashed" :key ?u)
     (:name "Today's messages"
            :query ,(concat "date:today..now "
                            "AND NOT maildir:/anuvyklack@gmail/[Gmail]/Корзина "
                            "AND NOT maildir:/anuvyklack@gmail/[Gmail]/Спам")
            :key ?t)
     (:name "Last 7 days"
            :query ,(concat "date:7d..now "
                            "AND NOT maildir:/anuvyklack@gmail/[Gmail]/Корзина "
                            "AND NOT maildir:/anuvyklack@gmail/[Gmail]/Спам ")
            :hide-unread t :key ?w)
     (:name "Archive" :query "maildir:/anuvyklack@gmail/Архив" :key ?a)
     ;; (:name "Messages with images"
     ;;        :query ,(concat "mime:image/*"
     ;;                        "AND NOT maildir:/anuvyklack@gmail/[Gmail]/Корзина "
     ;;                        "AND NOT maildir:/anuvyklack@gmail/[Gmail]/Спам ")
     ;;        :key ?p)
     ))
  (mu4e-refile-folder "/anuvyklack@gmail/Архив")
  ;; (mu4e-refile-folder "/anuvyklack@gmail/[Gmail]/Вся почта")
  (mu4e-sent-folder   "/anuvyklack@gmail/[Gmail]/Отправленные")
  (mu4e-drafts-folder "/anuvyklack@gmail/[Gmail]/Черновики")
  (mu4e-trash-folder  "/anuvyklack@gmail/[Gmail]/Корзина")
  (mu4e-maildir-shortcuts
   '((:maildir "/anuvyklack@gmail/[Gmail]/Отправленные" :key ?s)
     (:maildir "/anuvyklack@gmail/Архив" 								:key ?a)
     ;; (:maildir "/anuvyklack@gmail/Inbox"                :key ?i)
     (:maildir "/anuvyklack@gmail/[Gmail]/Вся почта"    :key ?A)
     (:maildir "/anuvyklack@gmail/[Gmail]/Корзина"      :key ?t)))
  (mu4e-headers-fields
   '((:human-date . 12)
     (:flags . 6)
     ;; (:mailing-list . 10)
     (:from . 25)
     (:subject)
     ;; (:thread-subject)
     ))
  (mu4e-sent-messages-behavior 'delete)
  (mu4e-change-filenames-when-moving t)
  (mu4e-update-interval (* 10 60))
  (mu4e-get-mail-command "mbsync -a")
  (mu4e-completing-read-function 'completing-read)
  (mu4e-search-skip-duplicates t)
  (mu4e-search-include-related t)
  :config
  ;; (add-to-list 'mu4e-bookmarks
  ;;     ;; ':favorite t' i.e, use this one for the modeline
  ;;    '(:query "maildir:/anuvyklack@gmail/Inbox" :name "Inbox" :key ?i :favorite t))
  (setf (plist-get (alist-get 'trash mu4e-marks) :action)
        (lambda (docid msg target)
          (mu4e--server-move docid (mu4e--mark-check-target target) "-N"))) ; Instead of "+T-N"
  (setq mu4e-use-fancy-chars nil)
  (setq mu4e-headers-draft-mark     '("D" . "")
        mu4e-headers-flagged-mark   '("F" . "")
        mu4e-headers-new-mark       '("N" . "")
        mu4e-headers-passed-mark    '("P" . "")
        mu4e-headers-replied-mark   '("R" . "")
        mu4e-headers-seen-mark      '("S" . "")
        mu4e-headers-trashed-mark   '("T" . "")
        mu4e-headers-attach-mark    '("a" . "📎")
        mu4e-headers-encrypted-mark '("x" . "")
        mu4e-headers-signed-mark    '("s" . "")
        mu4e-headers-unread-mark    '("u" . "")
        mu4e-headers-list-mark      '("l" . "")
        mu4e-headers-personal-mark  '("p" . "")
        mu4e-headers-calendar-mark  '("c" . ""))
  ;; (setq mu4e-headers-thread-child-prefix           '("├>" . "├─➤ ")
  ;;       mu4e-headers-thread-last-child-prefix    '("└>" . "└─➤ ")
  ;;       mu4e-headers-thread-orphan-prefix        '("┬>" . "┬─➤ ")
  ;;       mu4e-headers-thread-single-orphan-prefix   '("─>" . "──➤ ")
  ;;       ;; The following two should have the same width.
  ;;       mu4e-headers-thread-connection-prefix    '("│" . "│ ")
  ;;       mu4e-headers-thread-blank-prefix           '(" " . " "))
  (setq mu4e-headers-thread-orphan-prefix        '("◊ " . "◊ ")
        ;; mu4e-headers-thread-single-orphan-prefix '("◊ " . "◊ ")
        mu4e-headers-thread-single-orphan-prefix '("> " . "◊ ")
        mu4e-headers-thread-duplicate-prefix     '("≡ " . "≡ ")
        mu4e-headers-thread-root-prefix          '("□ " . "□ ")
        mu4e-headers-thread-first-child-prefix   '("○ " . "○ ")
        mu4e-headers-thread-child-prefix         '("├╴" . "├╴")
        mu4e-headers-thread-last-child-prefix    '("└╴" . "└╴")
        ;; mu4e-headers-thread-first-child-prefix   '("○ " . "○ ")
        ;; mu4e-headers-thread-child-prefix         '("├>" . "├>")
        ;; mu4e-headers-thread-last-child-prefix    '("└>" . "└>")
        ;; The following two should have the same width.
        mu4e-headers-thread-connection-prefix    '("│ " . "│ ")
        mu4e-headers-thread-blank-prefix         '("  " . "  "))
  )

(use-package smtpmail
  :custom
  (message-send-mail-function 'smtpmail-send-it)
  (starttls-use-gnutls t)
  (smtpmail-starttls-credentials '(("smtp.gmail.com" 587 nil nil)))
  (smtpmail-auth-credentials '(("smtp.gmail.com" 587 "anuvyklack@gmail.com" nil)))
  (smtpmail-default-smtp-server "smtp.gmail.com")
  (smtpmail-smtp-server "smtp.gmail.com")
  (smtpmail-smtp-service 587)

  ;; Don't keep message buffers around.
  (message-kill-buffer-on-exit t))

(use-package bufler
  :elpaca t
  :custom
  (bufler-columns '("Name" "Size" "Path"))
  :config
  (setq bufler-filter-buffer-modes (delete 'fundamental-mode bufler-filter-buffer-modes))
  ;; (add-to-list 'bufler-filter-buffer-modes 'org-roam-mode)
  (my/append-to-list 'bufler-filter-buffer-modes
                     '(org-roam-mode
                       magit-status-mode magit-refs-mode magit-log-mode
                       mu4e-main-mode)))

(use-package org
  :after evil
  :custom
  (org-catch-invisible-edits 'show-and-error)
  (org-startup-indented t)
  (org-special-ctrl-a/e t)
  (org-tags-column -80)
  (org-imenu-depth 8)
  (org-startup-with-inline-images t)
  (org-image-actual-width '(400))
  ;; (org-ellipsis " ")
  (org-ellipsis " ↴")
  ;; (org-src-window-setup 'split-window-right)
  (org-src-window-setup 'current-window) ;; edit in current window
  (org-edit-src-content-indentation 0)
  (org-src-preserve-indentation nil)
  (org-src-tab-acts-natively t)
  ;; (org-return-follows-link t)
  ;; (org-tab-follows-link t)
  (org-use-speed-commands nil)
  ;; (org-log-state-notes-into-drawer t)
  (org-link-descriptive t)
  (org-ctrl-k-protect-subtree t)
  (org-id-locations-file-relative t)
  ;; (org-indirect-buffer-display 'current-window)
  (org-list-allow-alphabetical t)
  (org-log-into-drawer t)
  ;; (org-startup-folded 'content)
  (org-startup-folded 'show2levels)
  (org-use-property-inheritance t)
  (org-src-tab-acts-natively t)
  (org-confirm-babel-evaluate nil)
  (org-src-fontify-natively t)
  (org-fontify-whole-heading-line t)
  (org-fontify-done-headline t)
  (org-fontify-quote-and-verse-blocks t)
  ;; (org-list-description-max-indent 20)
  ;; (org-list-demote-modify-bullet '(("+" . "-") ("-" . "+") ("*" . "+")))
  (org-list-indent-offset 1)
  (org-cycle-include-plain-lists 'integrate)
  ;; (org-todo-keywords '((sequence "TODO" "WAITING" "NEXT" "DOING" "|" "DONE" "CANCELED")))
  ;; (org-todo-keywords '((sequence "TODO" "WAITING" "NEXT" "STARTED" "|" "DONE" "CANCELED")))
  (org-todo-keywords '((sequence "TODO" "WAITING" "NEXT" "INPROGRES" "|" "DONE" "CANCELED")))
  (org-priority-highest 65) ;; A
  (org-priority-lowest 67)  ;; C
  (org-priority-default 67) ;; C
  (org-log-done 'time)
  (org-deadline-warning-days 14)
  (org-log-redeadline 'note)
  (org-log-reschedule nil)
  (org-agenda-window-setup 'reorganize-frame)
  (org-agenda-restore-windows-after-quit t)
  (org-agenda-include-diary nil)
  (org-pretty-entities t)
  (org-attach-store-link-p t)
  (org-attach-use-inheritance t)
  :config
  (setq org-file-apps '(("\\.pdf\\'" . "evince %s")
                        ("\\.djvu\\'" . "evince %s")
                        (auto-mode . emacs)
                        (directory . emacs)
                        ("\\.mm\\'" . default)
                        ("\\.x?html?\\'" . default)))
  (org-babel-do-load-languages 'org-babel-load-languages
                               '((sql . t)
                                 (shell . t)
                                 (emacs-lisp . t)
                                 (python . t)))
  (with-eval-after-load 'evil
    (define-advice forward-evil-paragraph
        (:around (orig-fun &rest args) use-default-paragraph-definiton-in-org)
      (if (derived-mode-p 'org-mode)
          (let ((paragraph-start (default-value 'paragraph-start))
                (paragraph-separate (default-value 'paragraph-separate)))
            (apply orig-fun args))
        (apply orig-fun args))))
  (defun my/org-setup-agenda-buffer-face ()
    (setq buffer-face-mode-face '(:family "iA Writer Mono S"))
    (buffer-face-mode))
  
  (add-hook 'org-agenda-mode-hook 'my/org-setup-agenda-buffer-face)
  (defun my/org-icons ()
    "Beautify org mode keywords."
    (setq prettify-symbols-alist
          (mapcan (lambda (x) (list x (cons (upcase (car x)) (cdr x))))
                  '(("#+begin_src" . "")
                    ("#+end_src" . "―")
                    ("#+begin_example" . "")
                    ("#+end_example" . "")
                    ("#+begin_quote" . "")
                    ("#+end_quote" . "")
                    ;; ("#+begin_quote" . "")
                    ;; ("#+end_quote" . "")
                    ;; ("#+header:" . ?)
                    ;; ("#+name:" . ?﮸)
                    ;; ("#+results:" . ?)
                    ;; ("#+call:" . ?)
                    ;; (":properties:" . ?)
                    ;; (":logbook:" . ?)
                    )))
    ;; (setq prettify-symbols-alist '(("TODO" . "")
    ;;                                ("WAIT" . "")
    ;;                                ("NOPE" . "")
    ;;                                ("DONE" . "")
    ;;                                ("[#A]" . "")
    ;;                                ("[#B]" . "")
    ;;                                ("[#C]" . "")
    ;;                                ("[ ]" . "")
    ;;                                ("[X]" . "")
    ;;                                ("[-]" . "")
    ;;                                ;; (":PROPERTIES:" . "")
    ;;                                ;; (":END:" . "―")
    ;;                                ;; ("#+STARTUP:" . "")
    ;;                                ;; ("#+TITLE: " . "")
    ;;                                ;; ("#+RESULTS:" . "")
    ;;                                ;; ("#+NAME:" . "")
    ;;                                ;; ("#+ROAM_TAGS:" . "")
    ;;                                ;; ("#+FILETAGS:" . "")
    ;;                                ;; ("#+HTML_HEAD:" . "")
    ;;                                ;; ("#+SUBTITLE:" . "")
    ;;                                ;; ("#+AUTHOR:" . "")
    ;;                                ;; (":Effort:" . "")
    ;;                                ;; ("SCHEDULED:" . "")
    ;;                                ;; ("DEADLINE:" . "")
    ;;                                ))
    (prettify-symbols-mode)))

(use-package org-roam
  :elpaca t
  :after org
  :init
  (when (version<= "29" emacs-version)
    (setq org-roam-database-connector 'sqlite-builtin))
  :custom
  (org-roam-directory (file-truename "~/notes"))
  (org-roam-completion-everywhere t)
  ;; (org-id-link-to-org-use-id 'create-if-interactive)
  (org-id-link-to-org-use-id 'use-existing)
  (org-roam-db-gc-threshold most-positive-fixnum)
  (org-roam-node-display-template (concat "${title:*} "
                                          (propertize "${tags:17}" 'face 'org-tag)))
  :config
  (org-roam-db-autosync-mode)
  ;; (add-to-list 'display-buffer-alist
  ;;              '("\\*org-roam\\*"
  ;;                (display-buffer-in-direction)
  ;;                (direction . right)
  ;;                (window-width . 0.33)
  ;;                (window-height . fit-window-to-buffer)))
  (defun org-roam-node-insert-immediate (arg &rest args)
    (interactive "P")
    (let ((args (cons arg args))
          (org-roam-capture-templates (list (append (car org-roam-capture-templates)
                                                    '(:immediate-finish t)))))
      (apply #'org-roam-node-insert args)))
  )

(use-package org-roam-dailies
  :after org-roam
  :custom
  (org-roam-dailies-directory "journal/")
  ;; (org-roam-dailies-capture-templates
  ;;  '(("d" "default" entry "* %<%I:%M %p>: %?"
  ;;     :if-new (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n"))))
  )

(use-package org-contrib
  :elpaca t
  :config
  (use-package org-eldoc
    ;; :config (org-eldoc-load)
    ))

(setq org-agenda-skip-scheduled-if-done nil
      org-agenda-skip-deadline-if-done nil
      org-agenda-include-deadlines t
      org-agenda-include-diary nil
      org-agenda-block-separator 61
      org-agenda-compact-blocks nil
      org-agenda-start-with-log-mode nil)

(setq org-agenda-prefix-format '((agenda . " %i %-14:c%?-12t% s")
                                 (todo . " %i %-14:c")
                                 (tags . " %i %-14:c")
                                 (search . " %i %-14:c")))

(use-package org-super-agenda
  :elpaca t
  ;; :after (org evil-org org-agenda)
  ;; :hook (org-agenda-mode . org-super-agenda-mode)
  :config
  (org-super-agenda-mode)
  ;; Fix problem with evil keybindings in org-super-agenda-mode.
  ;; https://github.com/alphapapa/org-super-agenda/issues/50#issuecomment-817432643
  (setq org-super-agenda-header-map nil))

(setq my/org-super-agenda-groups
      '((:name "Important"
               :priority "A"
               :tag ("money" "bills")
               :property "urgent")
        (:name "Overdue"
               :deadline past
               :order 2)
        (:name "Due Today"
               :deadline today
               :order 3)
        (:name "Current Taks"
               :todo "NEXT"
               :order 4)
        (:name "Personal"
               :habit t
               :tag "personal"
               :order 6)
        (:name "House"
               :category "house"
               :tag "house"
               :order 6)
        (:name "Subaru"
               :tag ("car" "subaru")
               :category "car"
               :order 6)
        (:name "Github"
               :tag "issue"
               :order 12)))

(setq org-agenda-custom-commands
      '(("n" "Agenda and all TODOs"
         (;; (agenda "" ((org-agenda-span 7)
          ;;             (org-super-agenda-groups
          ;;              '((:name "Today"
          ;;                       :time-grid t
          ;;                       :date today
          ;;                       :todo "TODAY"
          ;;                       :scheduled today
          ;;                       :order 1)
          ;;                (:discard (:anything t))))))
          (agenda "" ((org-super-agenda-groups nil)))
          (alltodo "" ((org-agenda-overriding-header "")
                       (org-super-agenda-groups my/org-super-agenda-groups)))))
        ("g" "Custom list of all TODO entries"
         ((alltodo "" ((org-agenda-overriding-header "")
                       (org-super-agenda-groups my/org-super-agenda-groups)))))))

(use-package org-fancy-priorities
  :elpaca t
  :hook (org-mode . org-fancy-priorities-mode)
  :custom
  ;; (org-fancy-priorities-list '("🟥" "🟧" "🟨" "🟩" "🟦" "🟪"))
  ;; (org-fancy-priorities-list '("" "" ""))
  (org-fancy-priorities-list '("" "" ""))
  ;; (org-fancy-priorities-list '("█" "█" "█"))
  ;; (org-fancy-priorities-list '("⯀" "⯀" "⯀"))
  ;; (org-fancy-priorities-list '("⬢" "⬢" "⬢"))
  ;; (org-fancy-priorities-list '("⬣" "⬣" "⬣"))
  (org-priority-faces
   '((?A :foreground "red" :weight bold)
     (?B :foreground "orange" :weight bold)
     (?C :foreground "Chartreuse3" :weight bold)))
  )

(use-package org-superstar
  :elpaca t
  :after org
  :custom
  (org-superstar-remove-leading-stars nil)
  (org-superstar-item-bullet-alist nil)
  (org-superstar-item-bullet-alist '(;; (?+ . ?●)
                                     ;; (?- . ?•)
                                     (?* . ?➤)))
  :hook (org-mode . org-superstar-mode))

(use-package org-tempo
  :after org
  :config
  (add-to-list 'org-structure-template-alist '("se" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("sh" . "src sh"))
  (add-to-list 'org-structure-template-alist '("sc" . "src cpp"))
  (add-to-list 'org-structure-template-alist '("sp" . "src python"))
  (add-to-list 'org-structure-template-alist '("sl" . "src lua"))
  (add-to-list 'org-structure-template-alist '("sf" . "src fennel"))
  (add-to-list 'org-structure-template-alist '("sr" . "src rust")))

(use-package org-inlinetask
  :after org
  :custom
  (org-cycle-max-level 14)
  (org-inlinetask-min-level 15))

(use-package org-ql
  :elpaca t)

(use-package org-appear
  :elpaca t
  :after org
  :custom
  (org-hide-emphasis-markers t)
  :hook (org-mode . org-appear-mode))

(use-package org-cliplink
  :elpaca t)

(use-package org-roam-ui
  :elpaca t
  :after org-roam
  :custom
  (org-roam-ui-sync-theme t)
  (org-roam-ui-follow t)
  (org-roam-ui-update-on-save t)
  (org-roam-ui-follow-mode t)
  (org-roam-ui-open-on-start nil))

(use-package org-transclusion
  :elpaca t
  :after evil-collection
  :config
  (set-face-attribute 'org-transclusion-fringe nil :foreground "green" :background "green")
  ;; (set-face-attribute 'org-transclusion-source-fringe nil :foreground "green" :background "green")
  )

(use-package org-auto-tangle
  :elpaca t
  :defer t
  :custom
  (org-auto-tangle-babel-safelist '("~/.config/emacs/README.org"))
  :hook (org-mode . org-auto-tangle-mode))

(use-package tex
  :elpaca auctex
  :init
  (setq TeX-auto-save t)
  (setq TeX-parse-self t)
  (setq-default TeX-master nil))

(use-package xenops
  :elpaca t
  :init
  (setq xenops-math-image-scale-factor 1.4)
  (setq xenops-cache-directory (expand-file-name "var/xenops"
                                                 user-emacs-directory))
  :hook
  (latex-mode . xenops-mode)
  (LaTeX-mode . xenops-mode)
  ;; (org-mode . xenops-mode)
  (xenops-mode . (lambda ()
                   (advice-remove 'org-fill-paragraph
                                  #'xenops-math-fill-paragraph-after-advice))))

(use-package doom-modeline
  :elpaca t
  ;; :elpaca (:host github :repo "seagle0128/doom-modeline"
  ;;                ;; :ref "aa0e2dd"
  ;;                :ref "379b45bffe7d67683f17c3e815797a082d8793d3")
  :custom
  (doom-modeline-height 30)
  (doom-modeline-buffer-file-name-style 'relative-from-project)
  (doom-modeline-icon t)
  (doom-modeline-major-mode-icon t)
  (doom-modeline-time-icon t)
  (doom-modeline-highlight-modified-buffer-name nil)
  :init
  (setq doom-modeline-support-imenu t)
  :config
  (doom-modeline-mode 1))

(use-package telega
  :elpaca t
  :defer t
  :custom
  (telega-directory (file-truename "~/.local/share/telega"))
  (telega-completing-read-function completing-read-function))

(use-package evil
  :elpaca t
  :init
  (setq-default evil-want-keybinding nil)
  :custom
  (evil-want-integration t)
  (evil-want-keybinding nil)
  (evil-want-C-u-scroll t)
  (evil-want-C-d-scroll t)
  (evil-want-C-i-jump t)
  ;; (evil-want-minibuffer t)
  (evil-want-fine-undo t)
  (evil-undo-system 'undo-redo)
  (evil-overriding-maps nil)
  ;; (evil-search-module 'evil-search)
  (evil-move-beyond-eol t)
  ;; (evil-ex-complete-emacs-commands 'always)
  (evil-shift-round t)
  (org-return-follows-link t)
  (evil-vsplit-window-right t)
  (evil-split-window-below t)
  :config
  (customize-set-variable 'evil-want-Y-yank-to-eol t)
  ;; (evil-select-search-module 'evil-search-module 'evil-search)
  (evil-select-search-module 'evil-search-module 'isearch)
  ;; (evil-ex-define-cmd "ls" 'ibuffer-jump)
  (evil-ex-define-cmd "ls" 'bufler)
  (evil-mode 1)
  ;; (advice-add :after 'evil-window-vsplit)
  (evil-define-command my/evil-save-modified-buffer-and-kill-it (file &optional bang)
    "Save the current buffer and kill it."
    :repeat nil
    (interactive "<f><!>")
    (when (buffer-modified-p)
      (evil-write nil nil nil file bang))
    (kill-this-buffer)
    ;; (ibuffer)
    (bufler)))

(use-package evil-collection
  :elpaca t
  :after evil
  :custom
  ;; SPC is my leader key, so forbid evil-collection to bind to it.
  (evil-collection-key-blacklist '("SPC"))
  (evil-collection-outline-bind-tab-p t)
  (evil-collection-setup-minibuffer t)
  (evil-collection-corfu-key-themes '(default tab-n-go))
  :config
  (evil-collection-init)
  (general-def :states 'motion
    "M-u" 'universal-argument
    "SPC" '(:keymap leader-map) ;; use 'Space' as leader key
    ";" '(:keymap semicolon-leader-map)
    ;; "<backspace>" 'evil-ex ;; evil command (:) state
    "<backspace>" 'execute-extended-command ;; emacs M-x
    "g h" 'evil-first-non-blank
    "g l" 'evil-end-of-line
    ;; "g b" 'ibuffer-jump
    "g b" 'bufler
    "C-s" 'evil-write
    "C-p" 'consult-yank-from-kill-ring
    "-" 'dired-jump
    "/" 'consult-line
    "?" 'evil-search-forward
    "z n" 'narrow-to-region
    "z w" 'widen
    "Z Z" 'my/evil-save-modified-buffer-and-kill-it
    "z =" 'flyspell-correct-wrapper
    "g <tab>" 'tab-new)
  
  (general-def :states 'normal
    "g a" 'describe-char)
  
  (general-def :states '(normal visual)
    "C-p" 'consult-yank-from-kill-ring)
  
  (general-def :states 'visual
    "z n" (lambda () (narrow-to-region) (evil-exit-visual-state)))
  (general-def :keymaps 'universal-argument-map
    "M-u" 'universal-argument-more)
  (general-def :states 'insert
    "C-l" 'right-char)
  (general-def :keymaps 'leader-map
    "h"  '(:keymap help-map :which-key "help")
    "p"  '(:keymap projectile-command-map :which-key "projectile")
    "n"  '(:keymap my/notes-map :which-key "notes")
    "m"  '(:keymap my/bookmark-map :which-key "bookmark")
    "b"  'consult-buffer
    "ff" 'find-file
    "fo" 'consult-outline
    "fg" 'consult-grep
    "fi" 'consult-imenu
    "fr" 'consult-recent-file
    "fd" 'consult-dir
    "fb" 'consult-bookmark
    "fv" 'vertico-repeat-select) ;; v for vertico
  (general-def :keymaps 'help-map
    "M" 'describe-keymap)
  (general-def :keymaps 'my/bookmark-map
    "m" 'consult-bookmark
    "n" 'bookmark-set
    "b" 'bookmark-set
    "d" 'bookmark-delete
    "l" 'bookmark-bmenu-list)
  (with-eval-after-load 'lsp-mode
    (general-def :keymaps 'leader-map
      "l" '(:keymap lsp-command-map :which-key "LSP")
      ;; "l" '(:keymap lsp-command-keymap :which-key "LSP")
      ))
  (general-def :keymaps 'corfu-map
    :states 'insert
    "<escape>" 'corfu-quit
    "C-l" 'corfu-insert)
  (with-eval-after-load 'vertico
    (general-def :keymaps 'vertico-map :states '(normal visual)
      "C-j" 'vertico-next
      "C-k" 'vertico-previous
      "C-l" 'vertico-insert
      "C-n" 'vertico-next-group
      "C-p" 'vertico-previous-group
      "C-f" 'vertico-scroll-up
      "C-b" 'vertico-scroll-down
      "C-d" 'consult-dir
      ;; "C-j" 'consult-dir-jump-file
      "gg" 'vertico-first
      "G"  'vertico-last
      "q" 'abort-recursive-edit)
  
    (general-def :keymaps 'vertico-map :states 'insert
      "C-y" 'yank
      "C-j" 'vertico-next
      "C-k" 'vertico-previous
      "C-l" 'vertico-insert
      "C-d" 'consult-dir
      "C-n" 'vertico-next-group
      "C-p" 'vertico-previous-group
      "C-f" 'vertico-scroll-up
      "C-b" 'vertico-scroll-down))
  (general-def :keymaps 'dired-mode-map :states 'normal
    "SPC" '(:keymap leader-map) ;; use 'Space' as leader key
    ;; "<backspace>" 'dired-up-directory
    "<backspace>" 'execute-extended-command ;; emacs M-x
    ;; "<tab>" 'dired-subtree-cycle
    "l" 'dired-find-file
    "h" 'dired-up-directory
    "f" 'find-file
    "r" 'dired-do-rename
    "y" 'dired-ranger-copy
    "p" 'dired-ranger-paste
    "P" 'dired-ranger-move
    "w" 'dired-display-file
    ")" 'dired-omit-mode
    "<" 'dired-prev-marked-file
    ">" 'dired-next-marked-file
    "." 'hydra-dired/body
    "M-RET" 'my/dired-xdg-open)
  
  (general-def :keymaps 'dired-mode-map :states 'visual
    "d" 'dired-flag-file-deletion
    "u" 'dired-unmark)
  (defhydra hydra-dired (:hint nil :color pink)
    "
  _Y_ rel symlink    _O_pen marked
  _S_ymlink          _n_ narrow
  _z_ compress-file  _m_ chmod        _s_ort           _E_ ediff
  _Z_ compress       _g_ chgrp        _e_xtension mark   _=_ pdiff
  "
    ("+" dired-maybe-create-dirs)
    ("=" diredp-ediff) ;; smart diff
    ("e" dired-mark-extension)
    ("E" dired-ediff-files)
    ("g" dired-do-chgrp)
    ("m" dired-do-chmod)
    ("n" dired-narrow)
    ("O" dired-do-find-marked-files) ;; open in Emacs all marked files
    ;; ("o" dired-display-file)
    ;; ("r" dired-do-rsynch)
    ("S" dired-do-symlink)
    ("s" dired-sort-toggle-or-edit)
    ("Y" dired-do-relsymlink)
    ("z" diredp-compress-this-file)
    ("Z" dired-do-compress)
    ("q" nil)
    ("." nil :color blue)
    ("<escape>" nil :color blue))
  (with-eval-after-load 'magit-section
    (general-def :keymaps 'magit-section-mode-map
      :states 'normal
      "g h" 'evil-first-non-blank
      "g l" 'evil-end-of-line
      "C-j" 'magit-section-forward-sibling
      "C-k" 'magit-section-backward-sibling
      "z j" 'magit-section-forward-sibling
      "z k" 'magit-section-backward-sibling
      "z u" 'magit-section-up
      "z t" 'evil-scroll-line-to-top
      "z z" 'evil-scroll-line-to-center
      "z b" 'evil-scroll-line-to-bottom)
  
    (general-def :keymaps 'with-editor-mode-map
      :states 'normal
      "SPC SPC" 'with-editor-finish
      "Q"  'with-editor-cancel
      "ZZ" 'with-editor-finish
      "ZQ" 'with-editor-cancel))
  (general-def :keymaps 'bufler-list-mode-map
    :states 'normal
    "<return>" 'bufler-list-buffer-switch
    "C-s" 'bufler-list-buffer-save
    "g r" '(bufler :which-key "refresh")
    "d" 'bufler-list-buffer-kill
    "x" 'bufler-list-buffer-kill
    "W" 'bufler-list-buffer-peek
    "?" 'hydra:bufler/body)
  (general-def
    :keymaps 'outline-mode-map
    :states 'normal
    "<tab>" 'outline-cycle
    "z j" 'outline-next-visible-heading
    "z k" 'outline-previous-visible-heading
    "z m" 'my/outline-hide-sublevels)
  (defun my/outline-hide-sublevels (levels)
    (interactive "p")
    (outline-hide-sublevels (or levels 1)))
  (general-def :keymaps 'my/orgmode-leader-map
    "SPC" 'org-ctrl-c-ctrl-c
    "n i" 'org-id-get-create
    "n p" 'org-set-property
    "n h" 'org-babel-insert-header-arg
    "l" 'org-insert-link
    "d" 'org-deadline
    "s" 'org-schedule
    "t" 'org-time-stamp
    "T" 'org-time-stamp-inactive
    "L" 'org-cliplink
    "a" 'org-attach
    "[" 'org-agenda-file-to-front
    "]" 'org-remove-file)
  (general-def :keymaps 'org-src-mode-map :states 'normal
    "z '" 'org-edit-src-exit)
  (with-eval-after-load 'org
    (general-def :keymaps 'org-mode-map :states '(normal visual)
      "g h" 'evil-org-beginning-of-line
      "g l" 'evil-org-end-of-line
      ;; "H" 'org-up-element
      ;; "L" 'org-down-element
      "g x" 'org-open-at-point
      "z n" 'org-narrow-to-subtree
      "z '" 'org-edit-special
      "z ," 'org-insert-structure-template
      "z /" 'org-sparse-tree
      "z ;" 'org-toggle-comment
      "SPC" '(:keymap my/orgmode-leader-map)
      "K" 'helpful-at-point)
  
    (general-def :keymaps 'org-mode-map
      :states 'insert
      "C-t" 'evil-shift-right-line
      "C-d" 'evil-shift-left-line))
  
  (add-hook 'evil-org-mode-hook
            (lambda ()
              (general-def :keymaps 'local :states 'insert
                "C-t" 'evil-shift-right-line
                "C-d" 'evil-shift-left-line)))
  (general-def
    :keymaps 'org-transclusion-map
    :states 'normal
    ;; "e" #'org-transclusion-live-sync-start
    ;; "g" #'org-transclusion-refresh
    ;; "d" #'org-transclusion-remove
    ;; "C-d" #'org-transclusion-detach
    ;; "P" #'org-transclusion-promote-subtree
    ;; "D" #'org-transclusion-demote-subtree
    ;; "o" #'org-transclusion-open-source
    ;; "O" #'org-transclusion-move-to-source
    "gi" #'org-transclusion-live-sync-start)
  (general-def
    :keymaps 'org-transclusion-live-sync-map
    :states 'normal
    ;; "C-c C-c" #'org-transclusion-live-sync-exit
    ;; "C-y" #'org-transclusion-live-sync-paste
    "q" #'org-transclusion-live-sync-exit)
  (general-def :keymaps 'my/notes-map
    "a" 'org-agenda
    "s" 'org-store-link
    "n" 'org-roam-node-find
    "c" 'org-roam-capture
    "b" 'org-roam-buffer-toggle
    "v" 'org-switchb
    "l" 'org-roam-node-insert
    "t" 'org-roam-tag-add
    "u" 'org-roam-ui-mode
    "d" '(:keymap org-roam-dailies-map))
  
  (general-def :keymaps 'org-roam-dailies-map
    "Y" 'org-roam-dailies-capture-yesterday
    "T" 'org-roam-dailies-capture-tomorrow)
  (general-def
    :keymaps 'Info-mode-map
    :states '(normal visual)
    "SPC" '(:keymap leader-map)
    "g H" 'Info-history
    "g L" 'Info-toc
    "C-j" 'Info-next
    "C-k" 'Info-prev
    "gj" 'Info-forward-node
    "gk" 'Info-backward-node))

(use-package evil-nerd-commenter
  :elpaca t
  :after evil
  :custom
  (evilnc-comment-text-object "c")
  :config
  (general-def
    :states 'motion
    "g c" 'evilnc-comment-operator))

(use-package evil-visualstar
  :elpaca t
  :after evil
  :config (global-evil-visualstar-mode))

(use-package evil-goggles
  :elpaca t
  :after evil
  :custom
  ;; (evil-goggles-duration 0.100) ;; default is 0.200
  (evil-goggles-enable-delete nil)
  ;; (evil-goggles-enable-change nil)
  :config
  (evil-goggles-mode)
  (evil-goggles-use-diff-faces))

(use-package evil-matchit
  :elpaca t
  :after evil
  :config (global-evil-matchit-mode 1))

(use-package evil-surround
  :elpaca t
  :after evil
  :config (global-evil-surround-mode 1))

(use-package evil-easymotion
  :elpaca t
  :after (avy evil)
  :config
  (evil-define-avy-motion avy-goto-word-0-above exclusive)
  (evil-define-avy-motion avy-goto-word-0-below exclusive)
  (evilem-make-motion evilem-motion-forward-WORD-begin  #'evil-forward-WORD-begin)
  (evilem-make-motion evilem-motion-backward-WORD-begin #'evil-backward-WORD-begin)
  (evilem-make-motion evilem-motion-forward-word-end    #'evil-forward-word-end)
  (evilem-make-motion evilem-motion-forward-WORD-end    #'evil-forward-WORD-end)
  (general-def
    :keymaps 'semicolon-leader-map
    "w" 'evil-avy-goto-word-0-below
    "W" 'evilem-motion-forward-WORD-begin
    "b" 'evil-avy-goto-word-0-above
    "B" 'evilem-motion-backward-WORD-begin
    "e" 'evilem-motion-forward-word-end
    "E" 'evilem-motion-forward-WORD-end
    "ge" 'evilem-motion-backward-word-end
    "gE" 'evilem-motion-backward-WORD-end
    "j" 'evilem-motion-next-visual-line
    "k" 'evilem-motion-previous-visual-line
    "f" 'evilem-motion-find-char
    "F" 'evilem-motion-find-char-backward))

(use-package evil-snipe
  :elpaca t
  :after evil
  :custom
  (evil-snipe-scope 'whole-visible)
  (evil-snipe-repeat-scope 'whole-visible)
  (evil-snipe-override-evil-repeat-keys nil)
  (evil-snipe-smart-case t)
  :config
  (evil-snipe-mode)
  (evil-snipe-override-mode)
  (push 'telega-root-mode evil-snipe-disabled-modes)
  ;; (push 'helpful-mode evil-snipe-disabled-modes)
  ;; (push 'Custom-mode evil-snipe-disabled-modes)
  ;; (define-key evil-snipe-parent-transient-map (kbd ";")
  ;;   (evilem-create 'evil-snipe-repeat
  ;;                  :bind ((evil-snipe-scope 'buffer)
  ;;                         (evil-snipe-enable-highlight)
  ;;                         (evil-snipe-enable-incremental-highlight))))
  )

(use-package evil-org
  ;; :elpaca t
  :load-path "~/code/emacs/evil-org-mode"
  :after (org evil evil-collection)
  :hook ((org-mode . evil-org-mode)
         (org-agenda-mode . (lambda ()
                              (require 'evil-org-agenda)
                              (evil-org-agenda-set-keys))))
  :config
  (evil-org-set-key-theme '(operators
                            textobjects
                            insert
                            ;; navigation
                            additional
                            ;; shift
                            todo
                            ;; heading
                            )))

(use-package evil-xkbswitch
  :elpaca (:host github :repo "linktohack/evil-xkbswitch")
  :after evil
  :diminish evil-xkbswitch-mode
  :config
  ;; If you use GNOME 41+:
  (setq evil-xkbswitch-set-layout "g3kb-switch -s"
        evil-xkbswitch-get-layout "g3kb-switch")
  (evil-xkbswitch-mode))

(use-package evil-anzu
  :elpaca t
  :after evil
  :bind (([remap query-replace] . anzu-query-replace)
         ([remap query-replace-regexp] . anzu-query-replace-regexp)))

(use-package ef-themes
  :elpaca t
  :after org
  :custom
  (ef-themes-mixed-fonts t)
  (ef-themes-variable-pitch-ui t)
  :config
  (load-theme 'ef-light :no-confirm)
  ;; (load-theme 'ef-day :no-confirm)
  (set-cursor-color "black")
  (set-face-attribute 'org-verbatim nil :foreground "#4250ef" :background "#f5f5f5")
  (set-face-attribute 'org-code     nil :foreground "#cf25aa" :background "#f5f5f5")
  (set-face-attribute 'org-level-1  nil :foreground "#375cd8" :weight 'normal :height 1.08)
  (set-face-attribute 'org-level-2  nil :foreground "#cf25aa" :weight 'normal :height 1.08)
  (set-face-attribute 'org-level-3  nil :foreground "#1f77bb" :weight 'normal :height 1.08)
  (set-face-attribute 'org-level-4  nil :foreground "#b65050" :weight 'normal :height 1.08)
  (set-face-attribute 'org-level-5  nil :foreground "#6052cf" :weight 'normal :height 1.08)
  ;; (set-face-attribute 'org-level-1  nil :foreground "#375cd8" :height 1.27)
  ;; (set-face-attribute 'org-level-2  nil :foreground "#cf25aa" :height 1.20)
  ;; (set-face-attribute 'org-level-3  nil :foreground "#1f77bb" :height 1.15)
  ;; (set-face-attribute 'org-level-4  nil :foreground "#b65050" :height 1.1)
  ;; (set-face-attribute 'org-level-5  nil :foreground "#6052cf" :height 1.05)
  )

(add-hook 'prog-mode-hook
          (lambda ()
            ;; (hs-minor-mode) ;; activate folding for all programming modes
            (setq show-trailing-whitespace t)))

(add-hook 'sh-mode-hook
          (lambda ()
            (setq sh-basic-offset 2
                  sh-indentation 2)))

(add-hook 'org-mode-hook
          (lambda ()
            (setq fill-column 80) ;; set textwidth to 80
            ;; Не показывать номера строк в орг-моде.
            (display-line-numbers-mode -1)
            (auto-revert-mode)
            (auto-fill-mode 1)
            ;; (visual-line-mode) ;; Wrap long lines on words.
            (my/org-icons)
            (setq-local tab-width 2)
            (setq-local evil-shift-width 2)))

(add-hook 'emacs-lisp-mode-hook
        (lambda ()
          (setq-local evil-shift-width  lisp-body-indent)
          ;; (message "evil-shift-width: %s" evil-shift-width)
          (setq tab-width lisp-body-indent)

          (require 'evil)
          ;; (evil-local-set-key 'normal (kbd "K") 'describe-symbol)
          (evil-local-set-key 'normal (kbd "K") #'helpful-at-point)

          ;; (evil-local-set-key 'normal "p" 'my/paste-and-indent-after)
          ;; (evil-local-set-key 'normal "P" 'my/paste-and-indent-before)
          ))

(use-package markdown-mode
  :elpaca t
  :mode ("README\\.md\\'" . gfm-mode)
  ;; :custom
  ;; (markdown-command "multimarkdown")
  )

(provide 'init.el)
;;; init.el ends here
