---
- name: Set up local workstation
  hosts: local
  roles:

    # - role: test
    #   tags:
    #     - test

    # - role: debian-testing
    #   when: ansible_distribution == 'Debian'
    #   tags:
    #     - debian-testing
    #   check_mode: yes

    - role: wsl
      when: ('WSL_DISTRO_NAME' in ansible_env) or ('IS_WSL' in ansible_env)
      tags:
        - wsl

    - role: apt
      when: ansible_pkg_mgr == 'apt'
      tags:
        - apt

    - role: git
      tags:
         git

    - role: alacritty
      tags:
        - alacritty

    - role: ripgrep
      tags:
        - ripgrep

    - role: bat
      tags:
        - bat

    - role: zsh
      tags:
        - zsh

    - role: ranger
      tags:
        - ranger

    - role: miniconda
      tags:
        - miniconda

    # - role: nodejs
    #   tags:
    #     - nodejs
    #   when: ansible_pkg_mgr == 'apt'

    - role: neovim
      tags:
        - neovim

    - role: power-managment
      tags:
        - power-managment

    - role: gnome3
      tags:
        - gnome

    - role: dual-function-keys
      tags:
        - keyboard

    - role: tmux
      tags:
        - tmux

    - role: vivaldi
      tags:
        - vivaldi

    # - role: lf
    #   tags:
    #     - lf

    # - role: far2l
    #   tags:
    #     - far2l

    # - role: notes-cli
    #   tags:
    #     - notes
