---
- name: Install apt packages
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600  # One hour
    state: present
    pkg:
      - wajig
      - man
      - anacron  # make sure that regular cron task are completed
      - curl
      - rsync
      - mlocate
      - fd-find
      - p7zip-full  # 7z archives
      - htop
      - ntfs-3g
      - qimgv    # image viewer

      # - x11-xkb-utils
      # - bfs      # find(1) c поиском в ширину в первую очередь
      # - par      # Paragraph formating utility for vim
      # - lua5.4

      # - exa      # a modern replacment for ls
      # - silversearcher-ag
      # - fzf      # fuzzy finder

- name: "Ensure {{ xdg_config_home }} directory exists"
  file:
    path: "{{ xdg_config_home }}"
    state: directory
