---
- name: install vifm (apt)
  become: yes
  apt:
    pkg:
      # - vifm
      # - python3-pip
      - poppler-utils    # pdf
      - tree
      - ncurses-term     # true color support
      - jq               # json
      - transmission-cli # torrent
      - ffmpegthumbnailer
      - antiword         # doc
      # - catdoc           # doc
    state: latest
    update_cache: yes
    cache_valid_time: 3600  # One hour
  when: ansible_pkg_mgr == 'apt'

- name: Make sure all vifm config folders are exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ config }}"
    - "{{ config }}/colors"

- name: Symlink vifm config files
  file:
    src: "{{ role_files }}/vifmrc"
    dest: "{{ config }}/vifmrc"
    state: link

- name: Symlink vifm color themes
  file:
    src: "{{ item.src }}"
    dest: "{{ config }}/colors/{{ item.path }}"
    state: link
  with_filetree: "{{ role_files }}/colors"
  loop_control:
    label: "{{ config }}/color/{{ item.path }}"

# - name: git clone color themes
#   git:
#     repo: https://github.com/vifm/vifm-colors
#     dest: "{{ home }}/.config/vifm/colors"
