;;; early-init.el -*- lexical-binding: t; no-byte-compile: t -*-
;;;
;;; Commentary:
;;; This file was automatically generated by `org-babel-tangle'.
;;; Do not change this file.  Main config is located in ~/.config/emacs/README.org
;;;
;;; Code:

(setq gc-cons-threshold most-positive-fixnum
      read-process-output-max (* 1024 1024 4) ; 4mb
      inhibit-compacting-font-caches t
      message-log-max 16384
      load-prefer-newer noninteractive)

(setopt tool-bar-mode nil
        menu-bar-mode nil
        scroll-bar-mode nil)

(setopt frame-inhibit-implied-resize t)

(when (featurep 'native-compile)
  (setq native-comp-async-report-warnings-errors 'silent))

(when (fboundp 'startup-redirect-eln-cache)
  (startup-redirect-eln-cache
    (convert-standard-filename
      (expand-file-name  "var/eln-cache/" user-emacs-directory))))

(setq load-prefer-newer t)
(when (require 'auto-compile nil t)
  (auto-compile-on-load-mode)
  (auto-compile-on-save-mode))

(provide 'early-init)
;;; early-init.el ends here
