# https://github.com/sindresorhus/pure

# PURE_PROMPT_SYMBOL=''
# PURE_PROMPT_VICMD_SYMBOL=''

# PURE_PROMPT_SYMBOL=''
# PURE_PROMPT_VICMD_SYMBOL=''


# PURE_GIT_DOWN_ARROW=''
# PURE_GIT_UP_ARROW=''
#
# PURE_GIT_DOWN_ARROW=''
# PURE_GIT_UP_ARROW=''
