# /etc/interception-tools/kinesis-advantage2.yaml
---
TIMING:
  TAP_MILLISEC: 200
  DOUBLE_TAP_MILLISEC: 0

MAPPINGS:
  - KEY: KEY_CAPSLOCK
    TAP: KEY_ESC
    HOLD: KEY_LEFTCTRL

  # - KEY: KEY_CAPSLOCK
  #   TAP: KEY_BACKSPACE

  - KEY: KEY_BACKSPACE
    TAP: KEY_BACKSPACE
    HOLD: KEY_RIGHTSHIFT
    HOLD_START: BEFORE_CONSUME

  - KEY: KEY_ESC
    TAP: KEY_ESC
    HOLD: KEY_LEFTCTRL

  - KEY: KEY_ENTER
    TAP: KEY_ENTER
    HOLD: KEY_LEFTSHIFT
    HOLD_START: BEFORE_CONSUME

  - KEY: KEY_SPACE
    TAP: KEY_SPACE
    HOLD: KEY_LEFTCTRL

  - KEY: KEY_LEFTSHIFT
    TAP: [ KEY_LEFTSHIFT, KEY_9, ]  # (
    HOLD: KEY_LEFTSHIFT

  - KEY: KEY_RIGHTSHIFT
    TAP: [ KEY_RIGHTSHIFT, KEY_0, ]  # )
    HOLD: KEY_RIGHTSHIFT
