---
- name: install ranger (apt)
  become: yes
  become_user: root
  become_method: sudo
  apt:
    pkg:
      - ranger
      - python3-pip
      - poppler-utils
    state: present
    force_apt_get: yes
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: pip install packages required for image preview
  pip:
    name:
      - ueberzug
      - pillow-simd
    state: latest

- name: check if ranger config already exists
  find:
    path: "{{ home }}/.config/ranger"
  register: ranger_config

# - debug: var=ranger_config

- name: symlink ranger config files
  file:
    src: "{{ role_path }}/files"
    dest: "{{ home }}/.config/ranger"
    state: link
    force: yes
  # Haven't found any files in ~/.config/ranger dir or
  # even haven't found ranger dir itself.
  when: ranger_config.matched == 0
  # check_mode: yes


- name: Copy ranger icon
  become: yes
  copy:
    src: ranger.png
    dest: /usr/share/pixmaps/ranger.png
    # owner: root
    # group: root
    force: no
    backup: yes

- name: Copy ranger.desktop file
  become: yes
  copy:
    src: ranger.desktop
    dest: /usr/share/applications/ranger.desktop
    # owner: root
    # group: root
    force: yes
    backup: yes
