---

- name: Ensure /etc/interception-tools dir exists
  become: yes
  file:
    path: /etc/interception-tools
    state: directory

- name: Symlink dual-function-keys config file
  become: yes
  file:
    src: "{{ role_path }}/files/dual-function-keys.yaml"
    dest: /etc/interception-tools/dual-function-keys.yaml
    state: link

- name: Symlink udevmon.yaml config file
  become: yes
  file:
    src: "{{ role_path }}/files/udevmon.yaml"
    dest: /etc/udevmon.yaml
    state: link

# - name: Symlink udevmon.service config file
#   become: yes
#   file:
#     src: "{{ role_path }}/files/udevmon.service"
#     dest: /etc/systemd/system/udevmon.service
#     state: link

- name: Copy udevmon.service file
  become: yes
  copy:
    # src: "{{ role_path }}/files/udevmon.service"
    src: udevmon.service
    dest: /etc/systemd/system/udevmon.service
    owner: root
    group: root
    backup: yes
