---

- name: Include variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_os_family }}.yaml"
      paths:
        - "vars"

- name: Install zsh and dependencies
  become: yes
  package:
    state: latest
    name: "{{ packages }}"

- name: Setup zsh as default shell for '{{ user_name }}'
  become: yes
  user:
    name: "{{ user_name }}"
    shell: /usr/bin/zsh

- name: Make sure all required folders are exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ home }}/.local/bin"
    - "{{ zshdir }}/settings"
    - "{{ zshdir }}/themes"

- name: Symlink zsh dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ role_files }}/zshenv",    dest: "{{ home }}/.zshenv" }
    - { src: "{{ role_files }}/zprofile",  dest: "{{ zshdir }}/.zprofile" }
    - { src: "{{ role_files }}/zshrc",     dest: "{{ zshdir }}/.zshrc" }
    - { src: "{{ role_files }}/zlogin",    dest: "{{ zshdir }}/.zlogin" }
    - { src: "{{ role_files }}/functions", dest: "{{ zshdir }}/functions" }
    - { src: "{{ role_files }}/dircolors", dest: "{{ zshdir }}/dircolors" }


- name: Link files in 'settings' folder
  file:
    src: "{{ item.src }}"
    dest: "{{ zshdir }}/settings/{{ item.path }}"
    state: link
  with_filetree: "{{ role_files }}/settings"
  loop_control:
    label: "{{ zshdir }}/settings/{{ item.path }}"


- name: Link files in 'themes' folder
  file:
    src: "{{ item.src }}"
    dest: "{{ zshdir }}/themes/{{ item.path }}"
    state: link
  with_filetree: "{{ role_files }}/themes"
  loop_control:
    label: "{{ zshdir }}/theme/{{ item.path }}"

- name: Link files in 'bin' folder
  file:
    src: "{{ item.src }}"
    dest: "{{ home }}/.local/bin/{{ item.path }}"
    state: link
  with_filetree: "{{ role_files }}/bin"
  loop_control:
    label: "{{ zshdir }}/bin/{{ item.path }}"
