---

- name: Install zsh and dependencies (apt)
  become: yes
  become_user: root
  become_method: sudo
  apt:
    pkg:
      - unzip
      - git
      - bfs
      # - lua5.4
      - zsh
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Setup zsh as default shell for '{{ user_name }}'
  become: yes
  user:
    name: "{{ user_name }}"
    shell: /usr/bin/zsh

- name: Make sure all required folders are exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ home }}/.local/bin"
    - "{{ zshdir }}/settings"
    - "{{ zshdir }}/themes"

- name: Symlink zsh dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ files }}/zshenv",    dest: "{{ home }}/.zshenv" }
    - { src: "{{ files }}/zprofile",  dest: "{{ zshdir }}/.zprofile" }
    - { src: "{{ files }}/zshrc",     dest: "{{ zshdir }}/.zshrc" }
    - { src: "{{ files }}/zlogin",    dest: "{{ zshdir }}/.zlogin" }
    - { src: "{{ files }}/functions", dest: "{{ zshdir }}/functions" }
    - { src: "{{ files }}/dircolors", dest: "{{ zshdir }}/dircolors" }


- name: Link files in 'settings' folder
  file:
    src: "{{ item.src }}"
    dest: "{{ zshdir }}/settings/{{ item.path }}"
    state: link
  with_filetree: "{{ files }}/settings"
  loop_control:
    label: "{{ zshdir }}/settings/{{ item.path }}"


- name: Link files in 'themes' folder
  file:
    src: "{{ item.src }}"
    dest: "{{ zshdir }}/themes/{{ item.path }}"
    state: link
  with_filetree: "{{ files }}/themes"
  loop_control:
    label: "{{ zshdir }}/theme/{{ item.path }}"

- name: Link files in 'bin' folder
  file:
    src: "{{ item.src }}"
    dest: "{{ home }}/.local/bin/{{ item.path }}"
    state: link
  with_filetree: "{{ files }}/bin"
  loop_control:
    label: "{{ zshdir }}/bin/{{ item.path }}"
