#!/bin/sh

# Распаковывать архивы командой 'extract <file>'
function extract {
  if [ -f $1 ]; then
    case $1 in
      *.tar.bz2) tar xvjf $1   ;;
      *.tar.gz)  tar xvzf $1   ;;
      *.tar.xz)  tar xvfJ $1   ;;
      *.bz2)     bunzip2 $1    ;;
      *.rar)     unrar x $1    ;;
      *.gz)      gunzip $1     ;;
      *.tar)     tar xvf $1    ;;
      *.tbz2)    tar xvjf $1   ;;
      *.tgz)     tar xvzf $1   ;;
      *.Z)       uncompress $1 ;;
      *.7z)      7z x $1       ;;
      *.zip)     unzip -d "$(basename -s '.zip' -- $1)" -- $1  ;;
      *)         echo "'$1' cannot be extracted via >extract<" ;;
    esac
  else
    # echo "'$1' is not a valid file"
    print $1 is not a valid file
  fi
}
