#!/bin/bash

function man {
    # if (( WIDTH > COLUMNS )); then
    #     MANWIDTH=$COLUMNS
    # fi

    LESSOPEN_ORIGINAL=$LESSOPEN
    export LESSOPEN="|- lesscenter %s"

    # export LESS_TERMCAP_mb=$'\E[1;31m'     # begin bold
    # export LESS_TERMCAP_md=$'\E[1;36m'     # begin blink
    # export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
    # export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video
    # export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
    # export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
    # export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

    # Use the old drawing scheme for bold and underline (using the backspace
    # character).  Colors are disabled.  See: `man grotty`
    export GROFF_NO_SGR=1

    command man $*

    export LESSOPEN=$LESSOPEN_ORIGINAL

    unset LESSOPEN_ORIGINAL
    unset GROFF_NO_SGR
}
