#!/usr/bin/env zsh

function n {
    if [[ "${NNNLVL:-0}" -ge 1 ]]; then
        echo "nnn is already running"
        return
    fi

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # NOTE: NNN_TMPFILE is fixed, should not be modified
    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    # Save original $LESS value.
    local LESS_ORIG=$LESS

    # The `-F` flag makes `less` exit immediately if the content fits
    # on one screen. However, this breaks the `nnn` help screen (`?`).
    # Remove all '-F' occurrences.
    LESS="${LESS_ORIG//-F/}"

    nnn "$@"

    # Restore original $LESS value.
    LESS=$LESS_ORIG

    if [[ -f "$NNN_TMPFILE" ]]; then
        . "$NNN_TMPFILE"
        rm -f "$NNN_TMPFILE" > /dev/null
    fi
}
