#!/usr/bin/env zsh

function print_title {
    local filler='―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――'
    local string="$(color white bold '――') $@"
    setopt local_options extended_glob
    local esc=$'\e'
    local stripped=${string//${esc}\[[0-9;]#m/}
    local string_length=${#stripped}
    print $string $(color white bold ${filler:0:-$string_length})
}
