---
- name: install kitty (apt)
  become: yes
  become_user: root
  become_method: sudo
  apt:
    name: kitty
    state: present
    force_apt_get: yes
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Symlink kitty config files
  file:
    src: "{{ role_path }}/files"
    dest: "{{ home }}/.config/kitty"
    state: link
