---
- name: install kitty (apt)
  become: yes
  become_user: root
  become_method: sudo
  apt:
    name: kitty
    state: present
    force_apt_get: yes
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Symlink kitty config files
  file:
    src: "{{ role_path }}/files"
    dest: "{{ home }}/.config/kitty"
    state: link

- name: get path to kitty bin
  shell: "which kitty"
  # shell: "command -v kitty"
  register: check_kitty
  changed_when: No

# - debug: var=check_kitty

# sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator `which kitty` 50
# sudo update-alternatives --config x-terminal-emulator
#
- name: "update-alternatives: x-terminal-emulator -> kitty"
  become: yes
  community.general.alternatives:
    name: x-terminal-emulator
    # link: /usr/bin/x-terminal-emulator
    path: "{{ check_kitty.stdout }}"
    priority: 50
