---

- name: Intall latest kitty with stow
  include_tasks: stow-kitty.yaml
  when: ansible_os_family == 'Debian'

- name: Make sure kitty config directories are exist
  file:
    dest: "{{ item }}"
    state: directory
  loop:
    - "{{ config }}"
    - "{{ config }}/color_themes"

# - debug:
#     var: "{{ item }}"
#   with_filetree: "{{ role_path }}/files"

- name: Symlink kitty config files
  file:
    src: "{{ role_files }}/kitty.conf"
    dest: "{{ config }}/kitty.conf"
    state: link

- name: Symlink kitty custom color_themes
  file:
    src: "{{ item.src }}"
    dest: "{{ config }}/color_themes/{{ item.path }}"
    state: link
  with_filetree: "{{ role_files }}/color_themes"
  loop_control:
    label: "~/.config/kitty/color_themes/{{ item.path }}"

- name: git clone color themes
  git:
    repo: "{{ item.repo }}"
    dest: "{{ config }}/color_themes/{{ item.dest }}"
  loop:
    - { repo: "https://github.com/kovidgoyal/kitty-themes.git", dest: kitty-themes }
  loop_control:
    label: "{{ item.dest }}"

- name: git clone kittens
  git:
    repo: "{{ item.repo }}"
    dest: "{{ config }}/kittens/{{ item.dest }}"
  loop:
    - { repo: "https://github.com/yurikhan/kitty-smart-tab.git", dest: kitty-smart-tab }
  loop_control:
    label: "{{ item.dest }}"

- name: Symlink kittens files
  file:
    src: "{{ config }}/kittens/{{ item.kitten }}/{{ item.file }}"
    dest: "{{ config }}/{{ item.file }}"
    state: link
  loop:
    - { kitten: kitty-smart-tab, file: smart_tab.py }
  loop_control:
    label: "{{ item.kitten }}/{{ item.file }}"


# # - debug: var=check_kitty
#
# # sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator $(which kitty) 50
# # sudo update-alternatives --config x-terminal-emulator
# #
# - name: "update-alternatives: x-terminal-emulator -> kitty"
#   become: yes
#   community.general.alternatives:
#     name: x-terminal-emulator
#     # link: /usr/bin/x-terminal-emulator
#     path: "{{ check_kitty.stdout }}"
#     priority: 50
