---

# -------------------------- Install from apt -----------------------------

# - name: install kitty (apt)
#   become: yes
#   become_user: root
#   become_method: sudo
#   apt:
#     name: kitty
#     state: present
#     force_apt_get: yes
#     update_cache: yes
#   when: ansible_pkg_mgr == 'apt'

# --------------------- Install from Github release -----------------------

- name: Check if kitty is installed
  shell: which kitty  # "command -v kitty"
  register: check_kitty
  failed_when: false
  changed_when: check_kitty.rc != 0

- set_fact:
    kitty_installed: "{{ true if check_kitty.rc == 0 else false }}"

# - debug: var=kitty_installed

- name: Get current version info
  command: kitty --version
  register: kitty_current_ver
  changed_when: no
  when: kitty_installed

- name: Get current version
  set_fact:
    kitty_current_ver: "{{ kitty_current_ver | regex_search('[0-9.]+') }}"
  when: kitty_installed

# - debug: var=kitty_current_ver

- name: Get latest release info
  uri:
    url: "{{ kitty_release }}"
    body_format: json
    return_content: yes
  register: latest_release

# - debug: var=latest_release.json.tag_name

- name: Get latest release version
  set_fact:
    kitty_latest_ver: "{{ latest_release.json.tag_name | regex_search('[0-9.]+') }}"

# - debug: var=kitty_latest_ver

- name: Delete old kitty version installed with package manager
  become: yes
  apt:
    name: kitty
    state: absent
  when:
    - ansible_pkg_mgr == 'apt'
    - kitty_installed
    - kitty_latest_ver is version(kitty_current_ver, '>')

- name: install stow (apt)
  become: yes
  apt:
    name: stow
    state: present
  when: ansible_pkg_mgr == 'apt'

# https://sw.kovidgoyal.net/kitty/binary/
- name: Download latest kitty release
  shell:
    cmd: "curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin dest={{ stow_dir }} launch=n"
    warn: false  # Do not rise warning about curl.
  register: download_latest_kitty
  when:
    - kitty_installed
    - kitty_latest_ver is version(kitty_current_ver, '>')

- name: Delete empty folders in 'kitty.app' directory
  command:
    cmd: find -type d -empty -delete
    chdir: "{{ stow_dir }}/kitty.app"
  when: download_latest_kitty is not skipped

- name: stow kitty application
  command:
    cmd: stow --restow kitty.app
    chdir: "{{ stow_dir }}"
  when: download_latest_kitty is not skipped

- name: Make sure kitty config directories are exist
  file:
    dest: "{{ item }}"
    state: directory
  loop:
    - "{{ config }}"
    - "{{ config }}/color_themes"

# - debug:
#     var: "{{ item }}"
#   with_filetree: "{{ role_path }}/files"

- name: Symlink kitty config files
  file:
    src: "{{ role_files }}/kitty.conf"
    dest: "{{ config }}/kitty.conf"
    state: link

# - name: Symlink kitty config files
#   file:
#     src: "{{ role_files }}/{{ item }}"
#     dest: "{{ config }}/{{ item }}"
#     state: link
#   loop:
#     - kitty.conf
#     - onedark.conf

- name: Symlink kitty custom color_themes
  file:
    src: "{{ item.src }}"
    dest: "{{ config }}/color_themes/{{ item.path }}"
    state: link
  with_filetree: "{{ role_files }}/color_themes"
  loop_control:
    label: "~/.config/kitty/color_themes/{{ item.path }}"

- name: git clone color themes
  git:
    repo: "{{ item.repo }}"
    dest: "{{ config }}/color_themes/{{ item.dest }}"
  loop:
    - { repo: "https://github.com/kovidgoyal/kitty-themes.git", dest: kitty-themes }
  loop_control:
    label: "{{ item.dest }}"


- name: git clone kittens
  git:
    repo: "{{ item.repo }}"
    dest: "{{ config }}/kittens/{{ item.dest }}"
  loop:
    - { repo: "https://github.com/yurikhan/kitty-smart-tab.git", dest: kitty-smart-tab }
  loop_control:
    label: "{{ item.dest }}"

- name: Symlink kittens files
  file:
    src: "{{ config }}/kittens/{{ item.kitten }}/{{ item.file }}"
    dest: "{{ config }}/{{ item.file }}"
    state: link
  loop:
    - { kitten: kitty-smart-tab, file: smart_tab.py }
  loop_control:
    label: "{{ item.kitten }}/{{ item.file }}"


# # - debug: var=check_kitty
#
# # sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator $(which kitty) 50
# # sudo update-alternatives --config x-terminal-emulator
# #
# - name: "update-alternatives: x-terminal-emulator -> kitty"
#   become: yes
#   community.general.alternatives:
#     name: x-terminal-emulator
#     # link: /usr/bin/x-terminal-emulator
#     path: "{{ check_kitty.stdout }}"
#     priority: 50
