background            #282c34
foreground            #abb2bf

cursor                #d0d0d0
selection_background  #444444

# black
color0                #282C34
color8                #5C6370

# red
color1                #E06C75
color9                #E06C75

# green
# color2                #86c38a
color2                #98C379
color10               #98C379
# color10               #94f936

# yellow
# yellow              #D1A166
color3                #D19A66
color11               #f5ffa7

# blue
color4                #61AFEF
color12               #85befd

# magenta
color5                #C678DD
color13               #dc5bfc
# color13               #FF00FF
# color5                #b9b5fc
# color13               #b9b5fc

# cyan
color6                #56B6C2
# color6                #85befd
color14               #85befd

# white
color7                #ABB2BF
color15               #FFFFFF
# color7                #dfdfdf
# color15               #dfdfdf

selection_foreground  #161718
