---

- name: Capture bin version
  shell: command -v bin >/dev/null 2>&1
  register: is_bin_exists
  ignore_errors: yes
  changed_when: no

- name: Download bin
  get_url:
    url: "https://github.com/marcosnils/bin/releases/download/v{{ bin_base_version }}/bin_{{ bin_base_version }}_Linux_x86_64"
    dest: /tmp/bin
    mode: 0770
  when: is_bin_exists.rc != 0
  notify:
    - remove bin install script

- name: Create all required folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ xdg_config_home }}/bin/"
    - "{{ home }}/.local/bin/"

- name: Check bin config exists
  stat:
    path: "{{ xdg_config_home }}/bin/config.json"
  register: bin_config_file

# - debug: var=bin_config_file

- name: Create bin config file
  template:
    src: bin-config.json.j2
    dest: "{{ xdg_config_home }}/bin/config.json"
    mode: 0660
  when: not bin_config_file.stat.exists

- name: Self manage bin
  shell: /tmp/bin install github.com/marcosnils/bin
  when: is_bin_exists.rc != 0

# vim: ft=yaml.ansible
