# - name: Install prerequisites
#   become: yes
#   package:
#     - curl
#     - jq

- name: Install bin
  include_tasks: bin.yaml

- name: Install pipx
  include_tasks: pipx.yaml
  when: ansible_os_family == 'Debian'

- name: Install packages
  become: yes
  dnf:
    pkg:
      - pipx
      - python3-argcomplete
  when: ansible_distribution == 'Fedora'

- name: Symlink bat config files
  file:
    src: "{{ role_files }}/bat"
    dest: "{{ xdg_config_home }}/bat"
    state: link

- name: Symlink ripgrep config files
  file:
    src: "{{ role_files }}/ripgrep"
    dest: "{{ xdg_config_home }}/rg"
    state: link

- name: Symlink topgrade config files
  file:
    src: "{{ role_files }}/topgrade.toml"
    dest: "{{ xdg_config_home }}/topgrade.toml"
    state: link

# vim: ft=yaml.ansible
