---
- name: Install bin
  include: bin.yaml

- name: Symlink ripgrep config files
  file:
    src: "{{ files }}/ripgrep"
    dest: "{{ config }}/rg"
    state: link

- name: Symlink topgrade config files
  file:
    src: "{{ files }}/topgrade.toml"
    dest: "{{ config }}/topgrade.toml"
    state: link

- name: Symlink bat config files
  file:
    src: "{{ files }}/bat"
    dest: "{{ config }}/bat"
    state: link
