#!/usr/bin/env zsh

install_missing_programs()
{
  # bin {{{
  if ! (( $+commands[bin] ))
  then
    # Fill the string up to 80 symbols with '―' char to the right.
    string="―― Installing $(color green 'bin') "; print ${(r:80::―:)string}

    emulate -L zsh

    bin_base_version=0.8.0
    wget -O /tmp/bin "https://github.com/marcosnils/bin/releases/download/v${bin_base_version}/bin_${bin_base_version}_Linux_x86_64"
    chmod 0770 /tmp/bin  # make executable

    # Create config file
    bin_config_file="$HOME/.config/bin/config.json";
    mkdir --parents $bin_config_file:h  # create parent directories
    if ! [ -s $bin_config_file ];
    then
      echo '{'                                             > $bin_config_file;
      echo "    \"default_path\" : \"$HOME/.local/bin\"," >> $bin_config_file;
      echo '    "bins": {}'                               >> $bin_config_file;
      echo '}'                                            >> $bin_config_file;
    fi

    # Install bin.
    if ! [ $(/tmp/bin list | grep github.com/marcosnils/bin) ]
    then
      /tmp/bin install github.com/marcosnils/bin
    fi

    rm /tmp/bin
    unset bin_base_version
    unset bin_config_file
  fi # }}}
  # rg {{{
  if ! (( $+commands[rg] ))
  then
    string="―― Installing $(color blue 'ripgrep') "; print ${(r:80::―:)string}
    echo
    bin install https://github.com/BurntSushi/ripgrep
    echo
  fi # }}}
  # bat {{{
  if ! (( $+commands[bat] ))
  then
    string="―― Installing $(color blue 'bat') "; print ${(r:80::―:)string}
    echo
    bin install https://github.com/sharkdp/bat
    echo
    print "\$ $(color green 'bat') cache --build"
    bat cache --build
    echo
  fi # }}}
  # exa {{{
  if ! (( $+commands[exa] ))
  then
    string="―― Installing $(color Yellow 'exa') "; print ${(r:80::―:)string}
    echo
    bin install https://github.com/ogham/exa
    echo
  fi # }}}
  # fzf {{{
  if ! (( $+commands[fzf] ))
  then
    string="―― Installing $(color Yellow 'fzf') "; print ${(r:80::―:)string}
    echo
    bin install https://github.com/junegunn/fzf
    echo
  fi # }}}
  # zoxide {{{
  if ! (( $+commands[zoxide] ))
  then
    string="―― Installing $(color Magenta 'zoxide') "; print ${(r:80::―:)string}
    echo
    bin install https://github.com/ajeetdsouza/zoxide
    echo
  fi # }}}
  # delta {{{
  if ! (( $+commands[delta] ))
  then
    string="―― Installing $(color green 'delta') "; print ${(r:80::―:)string}
    echo
    bin install https://github.com/dandavison/delta
    echo
  fi # }}}
  # topgrade {{{
  if ! (( $+commands[topgrade] ))
  then
    string="―― Installing $(color red 'topgrade') "; print ${(r:80::―:)string}
    echo
    bin install https://github.com/r-darwish/topgrade
    echo
  fi # }}}
  # dust {{{
  if ! (( $+commands[dust] ))
  then
    string="―― Installing $(color yellow 'dust') "; print ${(r:80::―:)string}
    echo
    bin install https://github.com/bootandy/dust
    echo
  fi # }}}
  # duf {{{
  if ! (( $+commands[duf] ))
  then
    string="―― Installing $(color blue 'duf') "; print ${(r:80::―:)string}
    echo
    bin install https://github.com/muesli/duf
    echo
  fi # }}}
  # broot {{{
  if ! (( $+commands[broot] ))
  then
    string="―― Installing $(color red 'broot') "; print ${(r:80::―:)string}
    echo
    bin install https://github.com/Canop/broot
    echo
  fi # }}}
  # mcfly {{{
  if ! (( $+commands[mcfly] ))
  then
    string="―― Installing $(color Magenta 'mcfly') "; print ${(r:80::―:)string}
    echo
    bin install https://github.com/cantino/mcfly
    echo
  fi # }}}

  # print Everything is installed
  unset string
}

# vim: tw=75 ts=2 sw=2 fdm=marker
