#!/bin/sh

# Переименование файлов. Надо набрать: `name file_name` и появится
# небольшой диалог, в котором необходимо будет ввести новое имя для файла.

name ()
{
    name=$1
    vared -c -p 'rename to: ' name
    command mv $1 $name
}

