#!/bin/sh

update()
{

  # Color codes {{{
  RESET="\e[0m"

  RED="\e[00;31m"
  GREEN="\e[00;32m"
  YELLOW="\e[00;33m"
  BLUE="\e[00;34m"
  PURPLE="\e[00;35m"
  CYAN="\e[00;36m"
  GRAY="\e[00;37m"

  BOLD_RED="\e[01;31m"
  BOLD_GREEN="\e[01;32m"
  BOLD_YELLOW="\e[01;33m"
  BOLD_BLUE="\e[01;34m"
  BOLD_PURPLE="\e[01;35m"
  BOLD_CYAN="\e[01;36m"
  BOLD_WHITE="\e[01;37m"

  BRIGHT_RED="\e[01;91m"
  BRIGHT_GREEN="\e[01;92m"
  BRIGHT_YELLOW="\e[01;93m"
  BRIGHT_BLUE="\e[01;94m"
  BRIGHT_PURPLE="\e[01;95m"
  BRIGHT_CYAN="\e[01;96m"
  BRIGHT_WHITE="\e[01;97m"
  # }}}

  sudo apt update --yes
  # sudo apt upgrade --yes
  sudo apt full-upgrade --yes
  sudo apt autoremove --yes
  sudo apt autoclean --yes

  # Update pip packages {{{

  # pip install -U $(pip freeze | cut -d '=' -f 1)

  # }}}

  # conda {{{
  if command -v conda > /dev/null 2>&1
  then

    # Remember the current conda environment if any.
    if [[ -n $CONDA_DEFAULT_ENV ]]
    then
        local conda_env=$CONDA_DEFAULT_ENV
    fi

    echo ''
    echo -e "${BRIGHT_GREEN}conda ${BOLD_WHITE}updating ${BOLD_YELLOW}base ${RESET}"

    conda activate base
    conda update conda --yes
    conda update --all --yes

    # echo ''
    # echo -e '\e[32;1mconda \e[37;1mupdating \e[33;1mnvim \e[0m'
    #
    # conda activate nvim
    # conda update --all --yes

    # Clear cache
    conda clean --all --yes

    # # Restore conda environment
    # if [[ -n conda_env ]]
    # then
    #     conda activate $conda_env
    # else
    #     conda deactivate
    # fi

    conda deactivate

  fi
  # }}}

  # Homebrew {{{
  if command -v brew > /dev/null 2>&1
  then
    echo -e "${BOLD_WHITE}Updating ${BOLD_YELLOW}Homebrew ${RESET}"
    brew update
    brew upgrade
  fi
  # }}}

  # Pipx apps {{{
  if command -v /usr/bin/pipx > /dev/null 2>&1
  then
    echo
    echo -e "${BOLD_WHITE}Updating ${BRIGHT_GREEN}Pipx ${BOLD_WHITE}apps ${RESET}"
    /usr/bin/pipx upgrade-all
  fi
  # }}}

  # Zinit {{{
  if command -v zinit > /dev/null 2>&1
  then
    echo
    echo -e "${BOLD_WHITE}Updating ${BRIGHT_PURPLE}Zinit ${RESET}"
    zinit self-update
    zinit update --all
  fi
  # }}}

  # Tmux plugins {{{
  TMUX_PLUGIN_MANAGER="${HOME}/.local/share/tmux/plugins/tpm/bin/update_plugins"
  if [[ -s $TMUX_PLUGIN_MANAGER ]]
  then
    echo
    echo -e "${BOLD_WHITE}Updating ${BRIGHT_GREEN}Tmux ${BOLD_WHITE}plugins ${RESET}"
    $TMUX_PLUGIN_MANAGER all
  fi
  # }}}

}

# vim: ft=zsh
