[
    ; (ranged_tag)
    (carryover_tag_set)
    (heading1)
    (heading2)
    (heading3)
    (heading4)
    (heading5)
    (heading6)
    ; (generic_list)
    (todo_item1)
    (todo_item2)
    (todo_item3)
    (todo_item4)
    (todo_item5)
    (todo_item6)
    (marker)
    (unordered_list1)
    (unordered_list2)
    (unordered_list3)
    (unordered_list4)
    (unordered_list5)
    (unordered_list6)
] @fold
