packages:
  - wajig
  - man
  - anacron  # make sure that regular cron task are completed
  - curl
  - rsync
  - plocate
  - fd-find
  - p7zip-full  # 7z archives
  - htop
  - ntfs-3g
  - qimgv    # image viewer
  # - x11-xkb-utils
  # - bfs      # find c поиском в ширину в первую очередь
  # - par      # Paragraph formating utility for vim
  # - lua5.4
  # - exa      # a modern replacment for ls
  # - silversearcher-ag
  # - fzf      # fuzzy finder
