#!/usr/bin/env zsh
#
#             ███                 ██
#            ░░██                ░░
#      ██████ ░██  █████   ██████ ██ ██████
#     ░░░░██  ░██ ██░░░██ ██░░░██░██░██░░░██
#        ██   ░██░██  ░██░██  ░██░██░██  ░██
#       ██    ░██░██  ░██░░██████░██░██  ░██
#  ██  ██████ ░██░░█████  ░░░░░██░██░██  ░██
# ░░  ░░░░░░  ░░  ░░░░░    █████ ░░ ░░   ░░
#                         ░░░░░
# This file was automatically generated by Emacs Org-Mode `org-babel-tangle'.
# Do not change this file. The main file is `README.org`.

{
  setopt LOCAL_OPTIONS EXTENDED_GLOB GLOB_DOTS
  autoload -U zrecompile

  array=(zprofile zshrc zlogin)
  for i in $array; do
    zrecompile -pq "${ZDOTDIR:-${HOME}}/.$i"
  done

  # Recompile all zsh or sh files.
  # for FILE in {$ZDOTDIR/**,$HOME/.cache/zsh/**}/*.*sh(#qN)
  if [[ -d ${ZDOTDIR} ]]; then
    for FILE in ${ZDOTDIR}/**/*.*sh(#qN); do
      zrecompile -pq $FILE
    done

    # Compile all functions in the single 'digest' file.
    zrecompile -pq "${ZDOTDIR}/functions.zwc" \
               $(echo -n $(find "${ZDOTDIR}"/functions/ -maxdepth 1 -type f))
  fi

  if [[ -d $ZSH[cache] ]]; then
    for FILE in $ZSH[cache]/**/*.*sh(#qN); do
      zrecompile -pq $FILE
    done
  fi

  # Delete all "*.zwc.old" files
  # (#qN) is glob qualifier which sets the NULL_GLOB option for the current
  # pattern, so it doesn't show message if no matches found.
  # for FILE in {$ZDOTDIR/**,$HOME/.cache/zsh/**}/*.zwc.old(#qN);
  for FILE in {${ZDOTDIR}/**,$ZSH[cache]/**}/*.zwc.old(#qN); do
    rm -f -- "$FILE"
  done

} &!

# vim: ts=2 sw=2
