#!/usr/bin/env zsh
#                     ██
#                    ░██
#      ██████  ██████░██████   █████  ██████  ██    ██
#     ░░░░██  ██░░░░ ░██░░░██ ██░░░██░██░░░██░██   ░██
#        ██  ░░█████ ░██  ░██░███████░██  ░██░░██ ░██
#       ██    ░░░░░██░██  ░██░██░░░░ ░██  ░██ ░░████
#  ██  ██████ ██████ ░██  ░██░░█████ ░██  ░██  ░░██
# ░░  ░░░░░░ ░░░░░░  ░░   ░░  ░░░░░  ░░   ░░    ░░
#
# This file is always sourced.
# Even when Zsh is launched to run a single command — with the `-c` option.

# For WSL
[[ "$(umask)" = "000" ]] && umask 022

export XDG_BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
# export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/runtime-$USER}" # or $UID

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
