#!/usr/bin/env zsh
#                                       ███ ██ ███
#                                      ██░ ░░ ░░██
#      ██████ ██████  ██████  █████   ░██   ██ ░██   █████
#     ░░░░██ ░██░░░██░░██░░█ ██░░░██ ██████░██ ░██  ██░░░██
#        ██  ░██  ░██ ░██ ░ ░██  ░██░░░██░ ░██ ░██ ░███████
#       ██   ░██████  ░██   ░██  ░██  ░██  ░██ ░██ ░██░░░░
#  ██  ██████░██░░░   ███   ░░█████   ░██  ░██ ░██ ░░█████
# ░░  ░░░░░░ ░██     ░░░     ░░░░░    ░░   ░░  ░░   ░░░░░
#            ░░
#
# Commands executed at login before zshrc.

# * WORDCHARS

# Non-alphanumeric chars treated as part of a word.
# You can tweak this if you'd prefer "C-w" to break on dot, underscore, etc.
export WORDCHARS='*?[]~=&;!#$%^(){}<>'

# * WSL

# - IS_WSL          :: exists in WSL 1
# - WSL_DISTRO_NAME :: exists in WSL 2
# - -n              :: true if length of string is non-zero
if [[ -n "$IS_WSL" || -n "$WSL_DISTRO_NAME" ]]; then
  # We are in wsl.
  export WINDOWS_HOST_IP=$(awk '/nameserver/ {print $2}' /etc/resolv.conf)
  export WINDOWS_USER="$(cmd.exe /C "echo %USERNAME%" 2>/dev/null | tr -d '\r')"
fi

# * Custom variables

export SOFTWARE="$HOME/soft"
export STOW_DIR="/usr/local/stow"
export LOCAL_STOW_DIR="$HOME/.local/stow"

# For scoping purposes, anonymous functions can be used. They will be
# automatically executed and then thrown away.
() {
  local DIRS=($SOFTWARE $LOCAL_STOW_DIR)
  for local DIR in $DIRS; do
    if [[ ! -d $DIR ]]; then
      mkdir -p $DIR
    fi
  done
}

# * Path

# Ensure path arrays do not contain duplicates.
typeset -gU path fpath cdpath mailpath

path+=(
  $XDG_BIN_HOME
  $XDG_CONFIG_HOME/doom-emacs/bin
  /usr/local/{bin,sbin}
  # /opt/visit/bin
  # /opt/ParaView-5.8.1/bin
)

# # The list of directories that cd searches.
# cdpath=(
#   $HOME/.config
#   $cdpath
# )

# * Proxy

export socks_proxy="socks://127.0.0.1:10808"
export http_proxy="http://127.0.0.1:10809"
export https_proxy="http://127.0.0.1:10809"

# * Homebrew

if whence /home/linuxbrew/.linuxbrew/bin/brew > /dev/null 2>&1; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

  # local BREWCACHE="$HOME/.cache/Homebrew/brewenv.zsh"
  #
  # if [[ ! -s $BREWCACHE(#q.md-7N) ]]; then
  #   /home/linuxbrew/.linuxbrew/bin/brew shellenv > $BREWCACHE 2> /dev/null
  # fi
  # source $BREWCACHE

  # Enable completion for brew and programs installes with brew.
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

# * Editors

export VISUAL="emacsclient --create-frame --alternate-editor=emacs"

if (( $+commands[hx] )); then
  export EDITOR='hx'
elif (( $+commands[nvim] )); then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi

export PAGER='less -R'

# * Man

# The width of the text column in the man.
export MANWIDTH=80

# Tie together the scalar $MANPATH and the array $manpath in the same way that
# $PATH and $path ties and ensure array do not contain duplicates.
typeset -T MANPATH manpath
typeset -gU manpath

# # Generate $MANPATH from the output of the `manpath` command
# export MANPATH=$(command manpath)

# # Use `bat` as a colorizing pager for `man`
# export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# * Less

# Set the default Less options. Mouse-wheel scrolling has been disabled
# -X and -F (exit if the content fits on one screen) to enable it.

# - -F :: Exit if the content fits on one screen
# - -g :: Highlights just the current match of any searched string.
# - -i :: Case-insensitive searches.
# - -M :: Shows more detailed prompt, including file position.
# - -N :: Shows line numbers (useful for source code viewing).
# - -R / --RAW-CONTROL-CHARS ::
# - -S :: Disables line wrap ("chop long lines"). Long lines can be seen by
#         side scrolling.
# - -X :: Leave file contents on screen when less exits.
# - -? :: Shows help.
# - +F :: Follow mode for log.
# - -w / --hilite-unread ::
#         Temporarily highlights the first "new" line after a forward movement
#         of a full page.
# - -z-3 :: Move page not on the full high of the screen but on high minus 3 lines

# export LESS='-F -i -M -R -S -w -z-3'
# export LESS='-F -i -M -R -S -z-3'
export LESS='-i -M -R -S -z-3'

# Set the Less input preprocessor. Try both `lesspipe` and `lesspipe.sh` as
# either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

export LESSHISTFILE="$HOME/.cache/lesshst"

# * Colored man pages

# export LESS_TERMCAP_mb=$'\e[01;31m'     # Begins blinking.
export LESS_TERMCAP_md=$'\e[01;97m'     # Begins bold.
export LESS_TERMCAP_so=$'\e[00;47;30m'  # Begins standout-mode.
export LESS_TERMCAP_us=$'\e[04;97m'     # Begins underline.
export LESS_TERMCAP_me=$'\e[0m'         # Ends mode.
export LESS_TERMCAP_se=$'\e[0m'         # Ends standout-mode.
export LESS_TERMCAP_ue=$'\e[0m'         # Ends underline.

# * LS_COLORS

# Tie together the scalar $LS_COLORS and the array $ls_colors in the same way
# that $PATH and $path ties.
typeset -T LS_COLORS ls_colors

# Specification:
#
#   LS_COLORS='di=1:fi=0:...:or=31:*.deb=90'
#
# The `*.deb=90` parameter above tells `ls` to display any files ending with
# a `.deb` extension using the color specified, 90 or dark grey in this case.
# This can be applied to any types of files (eg. you could use `*.jpg=33` to
# make JPEG files appear orange).
#
# The ; chars need to be escaped by \ (for example: di=1\;36), other way they
# somewhy will be converted to : chars. Or it is also work to enclose them in
# quotes.
export ls_colors=(
  'di=1;36'   # Directory : bold; cyan
  'fi=0'      # File : default
  'ln=35'     # Symbolic Link : purple
  'pi=33'     # Fifo file
  'so=32'     # Socket file
  'bd=30;46'  # Block (buffered) special file : black; cyan background
  'cd=34;43'  # Character (unbuffered) special file
  # 'or'        # (ORPHAN) Symbolic link pointing to an orphaned non-existent file
  # 'mi'        # Non-existent file pointed to by a symbolic link (visible when you type ls -l)
  'su=30;41'  # File that is setuid (u+s)
  'sg=30;46'  # File that is setgid (g+s)
  'tw=30;42'  # Directory that is sticky and other-writable (+t,o+w)
  'ow=30;43'  # Directory that is other-writable (o+w) and not sticky
  'ex=31'     # File which is executable (ie. has ‘x’ set in permissions).
)

# * Info

# # Tie together the scalar $INFOPATH and the array $infopath in the same way that
# # $PATH and $path ties.
# typeset -T INFOPATH infopath
#
# # Ensure array do not contain duplicates.
# typeset -gU infopath
#
# infopath+=(
#   /usr/share/info/
#   $HOME/.nix-profile/share/info
# )

# * bat
if (( $+commands[bat] )); then
  export BAT_PAGER="less ${LESS}"
  # export BAT_PAGER="less -RF"
fi

# * cmake
if (( $+commands[cmake] )); then
  export CMAKE_BUILD_PARALLEL_LEVEL=15
fi

# * home-manager

if (( $+commands[home-manager] )); then
  source $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh
fi

# * Emacs

# lsp-mode: use `plists` for deserialization
export LSP_USE_PLISTS=true

# * Par (paragraph formating)

export PARINIT="rTbgqR B=.,?'_A_a_@ Q=_s>|"

# * Ripgrep

if (( $+commands[rg] )); then
  export RIPGREP_CONFIG_PATH="$HOME/.config/rg/config"
fi

# * QT Applications

if [[ $XDG_SESSION_TYPE == 'wayland' ]]; then
    export QT_QPA_PLATFORM=wayland
fi
export QT_AUTO_SCREEN_SCALE_FACTOR=1

# * GTK

export GDK_BACKEND=wayland

# * .

# Local Variables:
# eval: (outli-mode 1)
# outline-blank-line: nil
# End:
