---

# - name: Install tmux
#   become: yes
#   apt:
#     name: tmux
#     state: present
#     update_cache: yes

- name: Build tmux from source
  include: build-tmux.yaml

- name: Symlink tmux config file
  file:
    src: "{{ role_files }}"
    dest: "{{ config }}"
    state: link

- name: Ensure tmux-plugin-manager folder exists
  file:
    path: "{{ tmux_plugin_manager }}"
    state: directory

- name: "Clone tmux-plugin-manager repo"
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ tmux_plugin_manager }}"

- name: Install tmux plugins
  command: "{{ tmux_plugin_manager }}/bin/install_plugins"

# vim: ft=yaml.ansible
