- name:
  include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_os_family }}.yaml"
      paths:
        - "tasks"
