---

- name: Backup original files
  become: yes
  command:
    cmd: mv --no-clobber '{{ item.path }}' '{{ item.path }}.original'
    chdir: /
    creates: '{{ item.path }}.original'
  when: item.state == 'file'
  failed_when: no
  with_filetree: "{{ role_path }}/files"
  loop_control:
    label: "/{{ item.path }}"
  # check_mode: yes

- name: Ensure required folders are exist
  become: yes
  file:
    path: "/{{ item.path }}"
    state: directory
  when: item.state == 'directory'
  with_filetree: "{{ role_path }}/files"
  loop_control:
    label: "/{{ item.path }}"

- name: Symlink config files
  become: yes
  file:
    src: "{{ item.src }}"
    dest: "/{{ item.path }}"
    state: link
  when: item.state == 'file'
  with_filetree: "{{ role_path }}/files"
  loop_control:
    label: "/{{ item.path }}"
  # check_mode: yes

# - debug:
#     var: item
#   when: item.state == 'file'
#   with_filetree: "{{ role_path }}/files"

- name: Symlink 'win32yank.exe' required for neovim to interact with Windows clipboard
  become: yes
  file:
    src: "/mnt/c/tools/win32yank.exe"
    dest: "/usr/local/bin/win32yank"
    state: link

- import_role:
    name: debian-testing
  when: ansible_distribution == 'Debian'
