theme = "monokai_pro_ristretto"
# theme = "melange"

[editor]
scrolloff = 0
auto-format = false
scroll-lines = 1 # default 3
rulers = [80]
insert-final-newline = true
completion-trigger-len = 1
true-color = true
color-modes = true
auto-pairs = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # deselect all; keep primary cursor only

# w = ["move_next_word_end", "move_prev_word_start", "move_next_word_end"] # select word under cursor
# W = ["move_next_long_word_end", "move_prev_long_word_start", "move_next_long_word_end"] # select WORD under cursor

p = "paste_before" # switched with P
P = "paste_after"  # switched with p
space.p = "paste_clipboard_before" # switched with P
space.P = "paste_clipboard_after" # switched with p

"X" = "select_line_above"

Z = { Z = ":x", Q = ":quit!" }

