---
- name: Install ripgrep
  become: yes
  apt:
    name: ripgrep
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Symlink ripgrep config files
  file:
    src: "{{ role_files }}"
    dest: "{{ xdg_config_home }}/rg"
    state: link
