---

# sudo dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
# sudo dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
- name: Enable RPM Fusion repositories
  become: yes
  shell:
    cmd: dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
    warn: false
  when: ansible_distribution == 'Fedora'

- name: Include variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_os_family }}.yaml"
        # - default.yaml
      paths:
        - "vars"

- name: Install packages based on the OS type
  become: yes
  package:
    state: latest
    name: "{{ packages }}"
  #   name: "{{ item }}"
  # loop: "{{ packages }}"

- name: "Ensure {{ xdg_config_home }} directory exists"
  file:
    path: "{{ xdg_config_home }}"
    state: directory
