---

# - debug: var=home

# - name: check if already installed
#   stat:
#     path: "{{ miniconda_home }}/bin/conda"
#   register: bin_conda
#   changed_when: bin_conda.stat.exists == False

- name: check if conda already installed
  shell: "command -v conda"
  register: check_conda
  failed_when: False
  changed_when: check_conda.rc != 0
  # ignore_errors: True
  # changed_when: no

# - debug: var=check_conda

- name: download miniconda installer
  get_url:
    url: "{{ miniconda_url }}"
    dest: /tmp/miniconda.sh
    mode: 0755
  register: miniconda_downloaded
  when: check_conda.rc != 0
  # when: check_conda is failed
  # when: bin_conda.stat.exists == False
  notify:
    - remove miniconda setup script

# - debug: var=miniconda_downloaded

- name: "install miniconda to {{ miniconda_home }}"
  become: yes
  # become_user: "{{ user_name }}"
  shell:
    cmd: "/tmp/miniconda.sh -b -p {{ miniconda_home }}"
    creates: "{{ miniconda_home }}"
    executable: /bin/bash
  register: miniconda_installed
  when:
    # miniconda_downloaded is succeeded and
    miniconda_downloaded is not skipped
  notify:
    - update conda to latest version

# - debug: var=miniconda_installed

- name: Ensure group "conda" exists
  become: yes
  group:
    name: conda
    state: present

- name: Recursively change ownership of miniconda directory
  become: yes
  file:
    path: "{{ miniconda_home }}"
    state: directory
    group: conda
    mode: '770'
    recurse: yes

- name: Add the user who run this role to 'conda' group
  become: yes
  user:
    name: "{{ user_name }}"
    groups: conda
    append: yes

- name: Ensure required directories are exists
  file:
    path: "{{ home }}/.jupyter"
    state: directory

- name: symlink condarc
  file:
    src: "{{ role_path }}/files/condarc"
    dest: "{{ home }}/.condarc"
    state: link

- name: symlink juyter qtconsole config
  file:
    src: "{{ role_path }}/files/jupyter_qtconsole_config.py"
    dest: "{{ home }}/.jupyter/jupyter_qtconsole_config.py"
    state: link
