---
- name: Install neovim (apt)
  become: yes
  apt:
    name:
      - curl
      - par  # Paragraph formating utility for vim / neovim
      - neovim
    state: present
    force_apt_get: yes  # Force usage of apt-get instead of aptitude
    update_cache: yes
    cache_valid_time: 3600  # One hour
  when: ansible_pkg_mgr == 'apt'

- name: Uninstall vim (apt)
  become: yes
  apt:
    state: absent
    force_apt_get: yes
    pkg:
      - vim
      - vim-common
      - vim-runtime
      - vim-tiny
  when: ansible_pkg_mgr == 'apt'

- name: Symlink neovim config files
  file:
    src: "{{ role_path }}/files"
    dest: "{{ home }}/.config/nvim"
    state: link


# Install conda environments
# --------------------------

# - name: Check if conda installed
#   shell: "command -v conda"
#   register: check_conda
#   ignore_errors: True
#   changed_when: no

# - name: Check if conda environments for neovim are already setup
#   shell: conda env list | awk '{print $1}' | grep -w '{{ env.name }}'
#   register: check_env
#   ignore_errors: True
#   changed_when: no
#   loop: "{{ miniconda_environments }}"
#   loop_control:
#     label: "{{ env.name }}"
#     loop_var: env  # Немая переменная по которрй будет производиться итерирование.

# - debug: var=check_env
# - debug: var=check_env.results

# - debug:
#     var: item.env.name
#     # msg: "{{ item.env.name }}"
#   loop: "{{ check_env.results }}"
#   loop_control:
#     label: "{{ item.env.name }}"

# - name: Create missing neovim conda environments
#   shell: "conda create -n {{ item.env.name }} {{ item.env.pkgs }}"
#   when: item is failed
#   loop: "{{ check_env.results }}"
#   loop_control:
#     label: "{{ item.env.name }}"
