---

- name: Include variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_os_family }}.yaml"
      paths:
        - "vars"

- name: Install neovim with dependencies
  become: yes
  package:
    state: latest
    name: "{{ packages }}"

- name: Uninstall vim
  when: packages_to_delete is defined
  become: yes
  package:
    name: "{{ packages_to_delete }}"
    state: absent

- name: Symlink neovim config files
  file:
    src: "{{ role_files }}"
    dest: "{{ config }}"
    state: link



# Install conda environments
# --------------------------

# - name: Check if conda installed
#   shell: "command -v conda"
#   register: check_conda
#   ignore_errors: True
#   changed_when: no

# - name: Check if conda environments for neovim are already setup
#   shell: conda env list | awk '{print $1}' | grep -w '{{ env.name }}'
#   register: check_env
#   ignore_errors: True
#   changed_when: no
#   loop: "{{ miniconda_environments }}"
#   loop_control:
#     label: "{{ env.name }}"
#     loop_var: env  # Немая переменная по которрй будет производиться итерирование.

# - debug: var=check_env
# - debug: var=check_env.results

# - debug:
#     var: item.env.name
#     # msg: "{{ item.env.name }}"
#   loop: "{{ check_env.results }}"
#   loop_control:
#     label: "{{ item.env.name }}"

# - name: Create missing neovim conda environments
#   shell: "conda create -n {{ item.env.name }} {{ item.env.pkgs }}"
#   when: item is failed
#   loop: "{{ check_env.results }}"
#   loop_control:
#     label: "{{ item.env.name }}"
